// Stage roster: 10 curated stages. spawnScript is each stage's COMPLETE wave
// list (no more hand-off into an endless/tier-scaled spawner once it's
// exhausted — Endless Mode and its shared spawner were removed; every enemy
// a stage will ever throw at the player is listed explicitly below, matching
// the bible's model of a stage as a finite, scripted encounter — §A.6.5).
// The only way to clear a stage is destroying its enemy base; if every
// scripted enemy is dead and the base isn't, the player just has to keep
// chipping at it with whatever's left on the field.
//
// Each stage:
//   id            stable key, also the localStorage progress key.
//   displayName   reskin hook / stage-select label.
//   difficulty    'Easy' | 'Normal' | 'Hard' | 'Boss' — just a label + the
//                 select-screen's accent color, doesn't affect gameplay math.
//   startingMoney, moneyAccrualPerSec, baseHp
//                 startingMoney doubles as this stage's level-1 Worker Cat
//                 wallet cap and moneyAccrualPerSec as its level-1 income
//                 rate (see MONEY_CONFIG.js's workerCat block and
//                 GameScene's getWalletCap/getMoneyAccrualPerSec — Worker
//                 Cat levels add flat increments on top of these per-stage
//                 baselines). Values are yen, matching Battle Cats' real
//                 "start each stage with 1000" convention (Easy 1.2x,
//                 Normal 1x, Hard 0.8x, Boss 1x of that base).
//   enemyBaseHp   the enemy tower's max HP — independent of baseHp (the
//                 player's own base) so it can climb with the difficulty
//                 curve instead of following the player-forgiveness curve.
//                 No fixed cap; scale it however high a stage calls for.
//   spawnScript   ordered, fixed list of enemies — no randomness, no
//                 tier-based auto-scaling. Each entry:
//                   enemyId          key into ENEMY_CONFIG.js
//                   statMultiplier   multiplies that enemy's base hp only
//                                    (1 = unscaled; the stage 10 boss uses 8)
//                   spawnDelayMs     time since the STAGE STARTED (not since
//                                    the previous spawn) — so entries must be
//                                    listed in increasing spawnDelayMs order.
//   baseXp        this stage's XP reward (bible §A.5.1) on a first clear;
//                 repeat clears taper toward a floor — see GameScene's
//                 getXpReward for the exact decay formula. This is the
//                 meta-progression XP (PlayerProgress.js), unrelated to
//                 the in-battle money economy above.
//   energyCost    stamina/Energy (bible §A.9, JP-confirmed term 統率力) spent
//                 to ENTER this stage at all — deducted (and entry blocked
//                 if insufficient) by StageSelectScene before GameScene ever
//                 starts; see Energy.js. Never refunded on a loss.
//   gemsFirstClear  a one-time Gems reward (bible §A.5's premium-currency
//                 equivalent) paid out ONLY the very first time this stage
//                 is won — distinct from the always-available XP/Treasure
//                 rewards above. See GameScene.winStage.
//   restrictions  optional (bible §A.6.5's Restriction Stage) — a modifier
//                 layer most stages omit entirely. Fields (any combo):
//                   maxDeployed       hard cap on simultaneously-alive
//                                     player units on the field at once
//                                     (well below the engine's implicit
//                                     "however many you can afford" limit).
//                   bannedUnitTypes   UNIT_CONFIG keys that can't be
//                                     deployed at all on this stage, even
//                                     though they're still in the Formation.
//                   costRange         { min, max } — a unit can't be
//                                     deployed unless its cost falls in
//                                     this (inclusive) band.
//                 All enforced in GameScene.trySpawnUnit, which shows a
//                 brief on-screen reason when a restriction blocks a tap.
//   Clearing a stage = reducing its enemy base's HP to 0 (see GameScene's
//   damageEnemyBase/winStage).

export const STAGE_CONFIG = [
  {
    id: 'stage1',
    saga: 'saga1',
    displayName: 'Training Grounds',
    difficulty: 'Easy',
    baseXp: 1000,
    energyCost: 5,
    gemsFirstClear: 20,
    startingMoney: 1200,
    moneyAccrualPerSec: 60,
    baseHp: 120,
    enemyBaseHp: 100,
    spawnScript: [
      { enemyId: 'basic', statMultiplier: 1, spawnDelayMs: 2000 },
      { enemyId: 'basic', statMultiplier: 1, spawnDelayMs: 6000 },
      { enemyId: 'fast', statMultiplier: 1, spawnDelayMs: 10000 },
      { enemyId: 'basic', statMultiplier: 1, spawnDelayMs: 14000 },
      { enemyId: 'fast', statMultiplier: 1, spawnDelayMs: 18000 },
      { enemyId: 'basic', statMultiplier: 1.1, spawnDelayMs: 22000 },
    ],
  },
  {
    id: 'stage2',
    saga: 'saga1',
    displayName: 'Basic Skirmish',
    difficulty: 'Easy',
    baseXp: 1200,
    energyCost: 6,
    gemsFirstClear: 25,
    startingMoney: 1200,
    moneyAccrualPerSec: 60,
    baseHp: 120,
    enemyBaseHp: 130,
    spawnScript: [
      { enemyId: 'basic', statMultiplier: 1, spawnDelayMs: 2000 },
      { enemyId: 'fast', statMultiplier: 1, spawnDelayMs: 5000 },
      { enemyId: 'basic', statMultiplier: 1, spawnDelayMs: 8000 },
      { enemyId: 'fast', statMultiplier: 1, spawnDelayMs: 11000 },
      { enemyId: 'basic', statMultiplier: 1.1, spawnDelayMs: 14000 },
      { enemyId: 'fast', statMultiplier: 1.1, spawnDelayMs: 17000 },
      { enemyId: 'basic', statMultiplier: 1.2, spawnDelayMs: 20000 },
      { enemyId: 'fast', statMultiplier: 1.2, spawnDelayMs: 23000 },
    ],
  },
  {
    id: 'stage3',
    saga: 'saga1',
    displayName: 'Fast Rush',
    difficulty: 'Easy',
    baseXp: 1400,
    energyCost: 7,
    gemsFirstClear: 30,
    startingMoney: 1200,
    moneyAccrualPerSec: 60,
    baseHp: 120,
    enemyBaseHp: 160,
    spawnScript: [
      { enemyId: 'fast', statMultiplier: 1, spawnDelayMs: 2000 },
      { enemyId: 'fast', statMultiplier: 1, spawnDelayMs: 4500 },
      { enemyId: 'basic', statMultiplier: 1.1, spawnDelayMs: 7000 },
      { enemyId: 'fast', statMultiplier: 1.1, spawnDelayMs: 9500 },
      { enemyId: 'fast', statMultiplier: 1.1, spawnDelayMs: 12000 },
      { enemyId: 'basic', statMultiplier: 1.2, spawnDelayMs: 15000 },
      { enemyId: 'fast', statMultiplier: 1.2, spawnDelayMs: 17500 },
      { enemyId: 'fast', statMultiplier: 1.3, spawnDelayMs: 20000 },
      { enemyId: 'basic', statMultiplier: 1.3, spawnDelayMs: 22500 },
    ],
  },
  {
    id: 'stage4',
    saga: 'saga1',
    displayName: 'Ranged Threat',
    difficulty: 'Normal',
    baseXp: 2000,
    energyCost: 8,
    gemsFirstClear: 35,
    startingMoney: 1000,
    moneyAccrualPerSec: 50,
    baseHp: 100,
    enemyBaseHp: 220,
    spawnScript: [
      { enemyId: 'basic', statMultiplier: 1, spawnDelayMs: 2000 },
      { enemyId: 'fast', statMultiplier: 1, spawnDelayMs: 5000 },
      { enemyId: 'ranged', statMultiplier: 1, spawnDelayMs: 8000 },
      { enemyId: 'basic', statMultiplier: 1.1, spawnDelayMs: 11000 },
      { enemyId: 'ranged', statMultiplier: 1.1, spawnDelayMs: 14000 },
      { enemyId: 'fast', statMultiplier: 1.2, spawnDelayMs: 17000 },
      { enemyId: 'ranged', statMultiplier: 1.2, spawnDelayMs: 20000 },
      { enemyId: 'basic', statMultiplier: 1.3, spawnDelayMs: 23000 },
      { enemyId: 'ranged', statMultiplier: 1.3, spawnDelayMs: 26000 },
    ],
  },
  {
    id: 'stage5',
    saga: 'saga1',
    displayName: 'Armor Up',
    difficulty: 'Normal',
    baseXp: 2500,
    energyCost: 9,
    gemsFirstClear: 40,
    startingMoney: 1000,
    moneyAccrualPerSec: 50,
    baseHp: 100,
    enemyBaseHp: 260,
    spawnScript: [
      { enemyId: 'basic', statMultiplier: 1, spawnDelayMs: 2000 },
      { enemyId: 'ranged', statMultiplier: 1, spawnDelayMs: 5000 },
      { enemyId: 'tank', statMultiplier: 1, spawnDelayMs: 8000 },
      { enemyId: 'fast', statMultiplier: 1.1, spawnDelayMs: 12000 },
      { enemyId: 'ranged', statMultiplier: 1.1, spawnDelayMs: 15000 },
      { enemyId: 'tank', statMultiplier: 1.1, spawnDelayMs: 18000 },
      { enemyId: 'basic', statMultiplier: 1.2, spawnDelayMs: 22000 },
      { enemyId: 'ranged', statMultiplier: 1.2, spawnDelayMs: 25000 },
      { enemyId: 'tank', statMultiplier: 1.2, spawnDelayMs: 28000 },
    ],
  },
  {
    id: 'stage6',
    saga: 'saga1',
    displayName: 'Combined Arms',
    difficulty: 'Normal',
    baseXp: 3000,
    energyCost: 10,
    gemsFirstClear: 45,
    startingMoney: 1000,
    moneyAccrualPerSec: 50,
    baseHp: 100,
    enemyBaseHp: 300,
    spawnScript: [
      { enemyId: 'fast', statMultiplier: 1.1, spawnDelayMs: 2000 },
      { enemyId: 'ranged', statMultiplier: 1.1, spawnDelayMs: 4500 },
      { enemyId: 'basic', statMultiplier: 1.1, spawnDelayMs: 7000 },
      { enemyId: 'tank', statMultiplier: 1.1, spawnDelayMs: 10000 },
      { enemyId: 'fast', statMultiplier: 1.2, spawnDelayMs: 14000 },
      { enemyId: 'ranged', statMultiplier: 1.2, spawnDelayMs: 16500 },
      { enemyId: 'tank', statMultiplier: 1.2, spawnDelayMs: 19000 },
      { enemyId: 'basic', statMultiplier: 1.3, spawnDelayMs: 22000 },
      { enemyId: 'ranged', statMultiplier: 1.3, spawnDelayMs: 24500 },
      { enemyId: 'tank', statMultiplier: 1.3, spawnDelayMs: 27000 },
    ],
  },
  {
    id: 'stage7',
    saga: 'saga1',
    displayName: 'All-Out Assault',
    difficulty: 'Hard',
    baseXp: 4000,
    energyCost: 12,
    gemsFirstClear: 55,
    startingMoney: 800,
    moneyAccrualPerSec: 42.5,
    baseHp: 90,
    enemyBaseHp: 380,
    spawnScript: [
      { enemyId: 'basic', statMultiplier: 1.2, spawnDelayMs: 1500 },
      { enemyId: 'fast', statMultiplier: 1.2, spawnDelayMs: 3500 },
      { enemyId: 'ranged', statMultiplier: 1.2, spawnDelayMs: 6000 },
      { enemyId: 'tank', statMultiplier: 1.2, spawnDelayMs: 9000 },
      { enemyId: 'aoe', statMultiplier: 1.2, spawnDelayMs: 12000 },
      { enemyId: 'fast', statMultiplier: 1.3, spawnDelayMs: 15000 },
      { enemyId: 'ranged', statMultiplier: 1.3, spawnDelayMs: 17500 },
      { enemyId: 'tank', statMultiplier: 1.3, spawnDelayMs: 20500 },
      { enemyId: 'aoe', statMultiplier: 1.3, spawnDelayMs: 23500 },
      { enemyId: 'basic', statMultiplier: 1.4, spawnDelayMs: 26000 },
    ],
  },
  {
    id: 'stage8',
    saga: 'saga1',
    displayName: 'Pressure Point',
    difficulty: 'Hard',
    baseXp: 5000,
    energyCost: 14,
    gemsFirstClear: 65,
    startingMoney: 800,
    moneyAccrualPerSec: 42.5,
    baseHp: 90,
    enemyBaseHp: 440,
    spawnScript: [
      { enemyId: 'fast', statMultiplier: 1.3, spawnDelayMs: 1500 },
      { enemyId: 'ranged', statMultiplier: 1.3, spawnDelayMs: 3000 },
      { enemyId: 'basic', statMultiplier: 1.3, spawnDelayMs: 4500 },
      { enemyId: 'tank', statMultiplier: 1.3, spawnDelayMs: 7000 },
      { enemyId: 'aoe', statMultiplier: 1.3, spawnDelayMs: 9500 },
      { enemyId: 'fast', statMultiplier: 1.4, spawnDelayMs: 12000 },
      { enemyId: 'ranged', statMultiplier: 1.4, spawnDelayMs: 13500 },
      { enemyId: 'tank', statMultiplier: 1.4, spawnDelayMs: 16000 },
      { enemyId: 'aoe', statMultiplier: 1.4, spawnDelayMs: 18500 },
      { enemyId: 'basic', statMultiplier: 1.5, spawnDelayMs: 21000 },
      { enemyId: 'ranged', statMultiplier: 1.5, spawnDelayMs: 22500 },
    ],
  },
  {
    id: 'stage9',
    saga: 'saga1',
    displayName: 'Gauntlet',
    difficulty: 'Hard',
    baseXp: 6000,
    energyCost: 16,
    gemsFirstClear: 75,
    startingMoney: 800,
    moneyAccrualPerSec: 42.5,
    baseHp: 90,
    // Restriction Stage (bible §A.6.5): forces lineup discipline instead of
    // just spamming everything at once.
    restrictions: { maxDeployed: 3 },
    enemyBaseHp: 500,
    spawnScript: [
      { enemyId: 'basic', statMultiplier: 1.4, spawnDelayMs: 1000 },
      { enemyId: 'fast', statMultiplier: 1.4, spawnDelayMs: 2500 },
      { enemyId: 'ranged', statMultiplier: 1.4, spawnDelayMs: 4500 },
      { enemyId: 'tank', statMultiplier: 1.4, spawnDelayMs: 7000 },
      { enemyId: 'aoe', statMultiplier: 1.4, spawnDelayMs: 9500 },
      { enemyId: 'fast', statMultiplier: 1.5, spawnDelayMs: 12000 },
      { enemyId: 'ranged', statMultiplier: 1.5, spawnDelayMs: 13500 },
      { enemyId: 'basic', statMultiplier: 1.5, spawnDelayMs: 15000 },
      { enemyId: 'tank', statMultiplier: 1.5, spawnDelayMs: 17500 },
      { enemyId: 'aoe', statMultiplier: 1.5, spawnDelayMs: 20000 },
      { enemyId: 'fast', statMultiplier: 1.6, spawnDelayMs: 22500 },
      { enemyId: 'ranged', statMultiplier: 1.6, spawnDelayMs: 24000 },
      { enemyId: 'tank', statMultiplier: 1.6, spawnDelayMs: 26500 },
    ],
  },
  {
    id: 'stage10',
    saga: 'saga1',
    displayName: 'The Overlord',
    difficulty: 'Boss',
    baseXp: 12000,
    energyCost: 25,
    gemsFirstClear: 150,
    startingMoney: 1000,
    moneyAccrualPerSec: 50,
    baseHp: 100,
    // Restriction Stage (bible §A.6.5): the boss fight bans the single
    // strongest unit outright, forcing a different lineup than "just bring
    // the best DPS."
    restrictions: { bannedUnitTypes: ['aoe'] },
    enemyBaseHp: 900,
    spawnScript: [
      { enemyId: 'fast', statMultiplier: 1.2, spawnDelayMs: 1000 },
      { enemyId: 'basic', statMultiplier: 1.2, spawnDelayMs: 3000 },
      { enemyId: 'ranged', statMultiplier: 1.3, spawnDelayMs: 6000 },
      { enemyId: 'tank', statMultiplier: 8, spawnDelayMs: 10000 }, // the boss
    ],
  },
  {
    id: 'stage11',
    saga: 'saga2',
    displayName: 'Swarm Warning',
    difficulty: 'Easy',
    baseXp: 13000,
    energyCost: 26,
    gemsFirstClear: 160,
    startingMoney: 1200,
    moneyAccrualPerSec: 60,
    baseHp: 120,
    enemyBaseHp: 950,
    spawnScript: [
      { enemyId: 'swarm', statMultiplier: 1, spawnDelayMs: 1000 },
      { enemyId: 'swarm', statMultiplier: 1, spawnDelayMs: 2200 },
      { enemyId: 'basic', statMultiplier: 1, spawnDelayMs: 3400 },
      { enemyId: 'swarm', statMultiplier: 1.1, spawnDelayMs: 4600 },
      { enemyId: 'fast', statMultiplier: 1.1, spawnDelayMs: 6000 },
      { enemyId: 'swarm', statMultiplier: 1.1, spawnDelayMs: 7200 },
      { enemyId: 'swarm', statMultiplier: 1.2, spawnDelayMs: 8400 },
      { enemyId: 'basic', statMultiplier: 1.2, spawnDelayMs: 9600 },
      { enemyId: 'swarm', statMultiplier: 1.2, spawnDelayMs: 10800 },
    ],
  },
  {
    id: 'stage12',
    saga: 'saga2',
    displayName: 'Numbers Game',
    difficulty: 'Easy',
    baseXp: 14500,
    energyCost: 27,
    gemsFirstClear: 175,
    startingMoney: 1200,
    moneyAccrualPerSec: 60,
    baseHp: 120,
    enemyBaseHp: 1050,
    spawnScript: [
      { enemyId: 'swarm', statMultiplier: 1.1, spawnDelayMs: 1000 },
      { enemyId: 'swarm', statMultiplier: 1.1, spawnDelayMs: 2000 },
      { enemyId: 'fast', statMultiplier: 1.1, spawnDelayMs: 3200 },
      { enemyId: 'swarm', statMultiplier: 1.2, spawnDelayMs: 4200 },
      { enemyId: 'swarm', statMultiplier: 1.2, spawnDelayMs: 5200 },
      { enemyId: 'basic', statMultiplier: 1.2, spawnDelayMs: 6400 },
      { enemyId: 'swarm', statMultiplier: 1.3, spawnDelayMs: 7400 },
      { enemyId: 'fast', statMultiplier: 1.3, spawnDelayMs: 8600 },
      { enemyId: 'swarm', statMultiplier: 1.3, spawnDelayMs: 9600 },
      { enemyId: 'swarm', statMultiplier: 1.3, spawnDelayMs: 10600 },
    ],
  },
  {
    id: 'stage13',
    saga: 'saga2',
    displayName: 'First Contact',
    difficulty: 'Normal',
    baseXp: 16500,
    energyCost: 29,
    gemsFirstClear: 195,
    startingMoney: 1000,
    moneyAccrualPerSec: 50,
    baseHp: 100,
    enemyBaseHp: 1200,
    spawnScript: [
      { enemyId: 'ranged', statMultiplier: 1.2, spawnDelayMs: 1500 },
      { enemyId: 'sniper', statMultiplier: 1, spawnDelayMs: 3500 },
      { enemyId: 'basic', statMultiplier: 1.2, spawnDelayMs: 5500 },
      { enemyId: 'swarm', statMultiplier: 1.3, spawnDelayMs: 7000 },
      { enemyId: 'sniper', statMultiplier: 1.1, spawnDelayMs: 9000 },
      { enemyId: 'tank', statMultiplier: 1.2, spawnDelayMs: 11500 },
      { enemyId: 'sniper', statMultiplier: 1.1, spawnDelayMs: 14000 },
      { enemyId: 'ranged', statMultiplier: 1.3, spawnDelayMs: 16000 },
    ],
  },
  {
    id: 'stage14',
    saga: 'saga2',
    displayName: 'Crossfire',
    difficulty: 'Normal',
    baseXp: 18500,
    energyCost: 31,
    gemsFirstClear: 215,
    startingMoney: 1000,
    moneyAccrualPerSec: 50,
    baseHp: 100,
    enemyBaseHp: 1350,
    spawnScript: [
      { enemyId: 'ranged', statMultiplier: 1.3, spawnDelayMs: 1500 },
      { enemyId: 'sniper', statMultiplier: 1.1, spawnDelayMs: 3000 },
      { enemyId: 'tank', statMultiplier: 1.3, spawnDelayMs: 5500 },
      { enemyId: 'aoe', statMultiplier: 1.3, spawnDelayMs: 8000 },
      { enemyId: 'sniper', statMultiplier: 1.2, spawnDelayMs: 10500 },
      { enemyId: 'ranged', statMultiplier: 1.4, spawnDelayMs: 12500 },
      { enemyId: 'tank', statMultiplier: 1.3, spawnDelayMs: 15000 },
      { enemyId: 'sniper', statMultiplier: 1.2, spawnDelayMs: 17500 },
      { enemyId: 'aoe', statMultiplier: 1.4, spawnDelayMs: 19500 },
    ],
  },
  {
    id: 'stage15',
    saga: 'saga2',
    displayName: 'Full Spectrum',
    difficulty: 'Normal',
    baseXp: 21000,
    energyCost: 33,
    gemsFirstClear: 240,
    startingMoney: 1000,
    moneyAccrualPerSec: 50,
    baseHp: 100,
    restrictions: { costRange: { min: 100, max: 500 } },
    enemyBaseHp: 1500,
    spawnScript: [
      { enemyId: 'basic', statMultiplier: 1.3, spawnDelayMs: 1000 },
      { enemyId: 'fast', statMultiplier: 1.3, spawnDelayMs: 2200 },
      { enemyId: 'ranged', statMultiplier: 1.4, spawnDelayMs: 3600 },
      { enemyId: 'tank', statMultiplier: 1.4, spawnDelayMs: 5400 },
      { enemyId: 'sniper', statMultiplier: 1.3, spawnDelayMs: 7400 },
      { enemyId: 'swarm', statMultiplier: 1.4, spawnDelayMs: 8600 },
      { enemyId: 'aoe', statMultiplier: 1.4, spawnDelayMs: 10600 },
      { enemyId: 'ranged', statMultiplier: 1.5, spawnDelayMs: 13000 },
      { enemyId: 'sniper', statMultiplier: 1.4, spawnDelayMs: 15000 },
      { enemyId: 'tank', statMultiplier: 1.4, spawnDelayMs: 17500 },
    ],
  },
  {
    id: 'stage16',
    saga: 'saga2',
    displayName: 'Toxic Ground',
    difficulty: 'Hard',
    baseXp: 24000,
    energyCost: 36,
    gemsFirstClear: 270,
    startingMoney: 800,
    moneyAccrualPerSec: 42.5,
    baseHp: 90,
    enemyBaseHp: 1700,
    spawnScript: [
      { enemyId: 'support', statMultiplier: 1, spawnDelayMs: 1500 },
      { enemyId: 'aoe', statMultiplier: 1.4, spawnDelayMs: 3500 },
      { enemyId: 'support', statMultiplier: 1.1, spawnDelayMs: 5500 },
      { enemyId: 'sniper', statMultiplier: 1.4, spawnDelayMs: 7500 },
      { enemyId: 'tank', statMultiplier: 1.5, spawnDelayMs: 9500 },
      { enemyId: 'support', statMultiplier: 1.2, spawnDelayMs: 11500 },
      { enemyId: 'aoe', statMultiplier: 1.5, spawnDelayMs: 13500 },
      { enemyId: 'sniper', statMultiplier: 1.5, spawnDelayMs: 16000 },
      { enemyId: 'support', statMultiplier: 1.2, spawnDelayMs: 18000 },
    ],
  },
  {
    id: 'stage17',
    saga: 'saga2',
    displayName: 'Siege Lines',
    difficulty: 'Hard',
    baseXp: 27000,
    energyCost: 39,
    gemsFirstClear: 300,
    startingMoney: 800,
    moneyAccrualPerSec: 42.5,
    baseHp: 90,
    enemyBaseHp: 1900,
    spawnScript: [
      { enemyId: 'tank', statMultiplier: 1.5, spawnDelayMs: 1500 },
      { enemyId: 'support', statMultiplier: 1.3, spawnDelayMs: 3500 },
      { enemyId: 'sniper', statMultiplier: 1.5, spawnDelayMs: 5500 },
      { enemyId: 'aoe', statMultiplier: 1.5, spawnDelayMs: 7500 },
      { enemyId: 'tank', statMultiplier: 1.6, spawnDelayMs: 9500 },
      { enemyId: 'support', statMultiplier: 1.4, spawnDelayMs: 11500 },
      { enemyId: 'sniper', statMultiplier: 1.6, spawnDelayMs: 13500 },
      { enemyId: 'swarm', statMultiplier: 1.5, spawnDelayMs: 15000 },
      { enemyId: 'aoe', statMultiplier: 1.6, spawnDelayMs: 16500 },
      { enemyId: 'tank', statMultiplier: 1.6, spawnDelayMs: 18500 },
    ],
  },
  {
    id: 'stage18',
    saga: 'saga2',
    displayName: 'Iron Wall',
    difficulty: 'Hard',
    baseXp: 30500,
    energyCost: 42,
    gemsFirstClear: 335,
    startingMoney: 800,
    moneyAccrualPerSec: 42.5,
    baseHp: 90,
    enemyBaseHp: 2150,
    spawnScript: [
      { enemyId: 'guardian', statMultiplier: 1, spawnDelayMs: 1500 },
      { enemyId: 'support', statMultiplier: 1.4, spawnDelayMs: 3500 },
      { enemyId: 'sniper', statMultiplier: 1.6, spawnDelayMs: 5500 },
      { enemyId: 'guardian', statMultiplier: 1.1, spawnDelayMs: 8000 },
      { enemyId: 'tank', statMultiplier: 1.6, spawnDelayMs: 10500 },
      { enemyId: 'aoe', statMultiplier: 1.6, spawnDelayMs: 12500 },
      { enemyId: 'guardian', statMultiplier: 1.1, spawnDelayMs: 15000 },
      { enemyId: 'sniper', statMultiplier: 1.7, spawnDelayMs: 17500 },
      { enemyId: 'support', statMultiplier: 1.5, spawnDelayMs: 19500 },
    ],
  },
  {
    id: 'stage19',
    saga: 'saga2',
    displayName: 'The Gauntlet II',
    difficulty: 'Hard',
    baseXp: 34500,
    energyCost: 45,
    gemsFirstClear: 375,
    startingMoney: 800,
    moneyAccrualPerSec: 42.5,
    baseHp: 90,
    restrictions: { maxDeployed: 4 },
    enemyBaseHp: 2400,
    spawnScript: [
      { enemyId: 'swarm', statMultiplier: 1.5, spawnDelayMs: 1000 },
      { enemyId: 'basic', statMultiplier: 1.5, spawnDelayMs: 2200 },
      { enemyId: 'ranged', statMultiplier: 1.6, spawnDelayMs: 3600 },
      { enemyId: 'sniper', statMultiplier: 1.7, spawnDelayMs: 5400 },
      { enemyId: 'tank', statMultiplier: 1.7, spawnDelayMs: 7400 },
      { enemyId: 'support', statMultiplier: 1.5, spawnDelayMs: 9400 },
      { enemyId: 'guardian', statMultiplier: 1.2, spawnDelayMs: 11800 },
      { enemyId: 'aoe', statMultiplier: 1.7, spawnDelayMs: 14200 },
      { enemyId: 'sniper', statMultiplier: 1.7, spawnDelayMs: 16600 },
      { enemyId: 'guardian', statMultiplier: 1.2, spawnDelayMs: 19000 },
      { enemyId: 'tank', statMultiplier: 1.7, spawnDelayMs: 21400 },
    ],
  },
  {
    id: 'stage20',
    saga: 'saga2',
    displayName: 'Overlord\'s Herald',
    difficulty: 'Boss',
    baseXp: 60000,
    energyCost: 55,
    gemsFirstClear: 600,
    startingMoney: 1000,
    moneyAccrualPerSec: 50,
    baseHp: 100,
    restrictions: { bannedUnitTypes: ['guardian'] },
    enemyBaseHp: 5000,
    spawnScript: [
      { enemyId: 'sniper', statMultiplier: 1.5, spawnDelayMs: 1000 },
      { enemyId: 'support', statMultiplier: 1.4, spawnDelayMs: 3000 },
      { enemyId: 'swarm', statMultiplier: 1.5, spawnDelayMs: 5000 },
      { enemyId: 'ranged', statMultiplier: 1.6, spawnDelayMs: 7500 },
      { enemyId: 'guardian', statMultiplier: 9, spawnDelayMs: 11000 },
    ],
  },
  {
    id: 'stage21',
    saga: 'saga3',
    displayName: 'Titan Sighting',
    difficulty: 'Easy',
    baseXp: 45000,
    energyCost: 48,
    gemsFirstClear: 450,
    startingMoney: 1200,
    moneyAccrualPerSec: 60,
    baseHp: 120,
    enemyBaseHp: 3200,
    spawnScript: [
      { enemyId: 'swarm', statMultiplier: 1.6, spawnDelayMs: 1000 },
      { enemyId: 'basic', statMultiplier: 1.6, spawnDelayMs: 2200 },
      { enemyId: 'sniper', statMultiplier: 1.7, spawnDelayMs: 3800 },
      { enemyId: 'support', statMultiplier: 1.6, spawnDelayMs: 5600 },
      { enemyId: 'titan', statMultiplier: 1, spawnDelayMs: 8000 },
      { enemyId: 'swarm', statMultiplier: 1.7, spawnDelayMs: 10000 },
      { enemyId: 'guardian', statMultiplier: 1.3, spawnDelayMs: 12000 },
    ],
  },
  {
    id: 'stage22',
    saga: 'saga3',
    displayName: 'Ground Shakers',
    difficulty: 'Easy',
    baseXp: 50000,
    energyCost: 50,
    gemsFirstClear: 480,
    startingMoney: 1200,
    moneyAccrualPerSec: 60,
    baseHp: 120,
    enemyBaseHp: 3500,
    spawnScript: [
      { enemyId: 'titan', statMultiplier: 1, spawnDelayMs: 1500 },
      { enemyId: 'fast', statMultiplier: 1.6, spawnDelayMs: 3500 },
      { enemyId: 'ranged', statMultiplier: 1.7, spawnDelayMs: 5500 },
      { enemyId: 'titan', statMultiplier: 1.1, spawnDelayMs: 8000 },
      { enemyId: 'swarm', statMultiplier: 1.7, spawnDelayMs: 10000 },
      { enemyId: 'guardian', statMultiplier: 1.3, spawnDelayMs: 12000 },
      { enemyId: 'titan', statMultiplier: 1.1, spawnDelayMs: 14500 },
    ],
  },
  {
    id: 'stage23',
    saga: 'saga3',
    displayName: 'Vanguard\'s Edge',
    difficulty: 'Normal',
    baseXp: 57000,
    energyCost: 53,
    gemsFirstClear: 520,
    startingMoney: 1000,
    moneyAccrualPerSec: 50,
    baseHp: 100,
    enemyBaseHp: 3900,
    spawnScript: [
      { enemyId: 'sniper', statMultiplier: 1.8, spawnDelayMs: 1500 },
      { enemyId: 'support', statMultiplier: 1.7, spawnDelayMs: 3500 },
      { enemyId: 'titan', statMultiplier: 1.1, spawnDelayMs: 6000 },
      { enemyId: 'guardian', statMultiplier: 1.4, spawnDelayMs: 8500 },
      { enemyId: 'swarm', statMultiplier: 1.8, spawnDelayMs: 10500 },
      { enemyId: 'sniper', statMultiplier: 1.8, spawnDelayMs: 12500 },
      { enemyId: 'titan', statMultiplier: 1.2, spawnDelayMs: 15000 },
      { enemyId: 'tank', statMultiplier: 1.8, spawnDelayMs: 17500 },
    ],
  },
  {
    id: 'stage24',
    saga: 'saga3',
    displayName: 'Corrosive Front',
    difficulty: 'Normal',
    baseXp: 64000,
    energyCost: 56,
    gemsFirstClear: 560,
    startingMoney: 1000,
    moneyAccrualPerSec: 50,
    baseHp: 100,
    enemyBaseHp: 4300,
    spawnScript: [
      { enemyId: 'support', statMultiplier: 1.8, spawnDelayMs: 1500 },
      { enemyId: 'aoe', statMultiplier: 1.8, spawnDelayMs: 3500 },
      { enemyId: 'titan', statMultiplier: 1.2, spawnDelayMs: 6000 },
      { enemyId: 'support', statMultiplier: 1.9, spawnDelayMs: 8500 },
      { enemyId: 'guardian', statMultiplier: 1.5, spawnDelayMs: 10500 },
      { enemyId: 'sniper', statMultiplier: 1.9, spawnDelayMs: 12500 },
      { enemyId: 'titan', statMultiplier: 1.3, spawnDelayMs: 15000 },
      { enemyId: 'aoe', statMultiplier: 1.9, spawnDelayMs: 17500 },
    ],
  },
  {
    id: 'stage25',
    saga: 'saga3',
    displayName: 'Full Roster',
    difficulty: 'Normal',
    baseXp: 72000,
    energyCost: 59,
    gemsFirstClear: 610,
    startingMoney: 1000,
    moneyAccrualPerSec: 50,
    baseHp: 100,
    restrictions: { costRange: { min: 400, max: 1600 } },
    enemyBaseHp: 4800,
    spawnScript: [
      { enemyId: 'basic', statMultiplier: 1.7, spawnDelayMs: 1000 },
      { enemyId: 'fast', statMultiplier: 1.7, spawnDelayMs: 2200 },
      { enemyId: 'ranged', statMultiplier: 1.8, spawnDelayMs: 3600 },
      { enemyId: 'tank', statMultiplier: 1.8, spawnDelayMs: 5400 },
      { enemyId: 'sniper', statMultiplier: 1.9, spawnDelayMs: 7400 },
      { enemyId: 'guardian', statMultiplier: 1.5, spawnDelayMs: 9800 },
      { enemyId: 'support', statMultiplier: 1.9, spawnDelayMs: 12000 },
      { enemyId: 'aoe', statMultiplier: 1.9, spawnDelayMs: 14200 },
      { enemyId: 'titan', statMultiplier: 1.3, spawnDelayMs: 16600 },
      { enemyId: 'swarm', statMultiplier: 1.9, spawnDelayMs: 18600 },
    ],
  },
  {
    id: 'stage26',
    saga: 'saga3',
    displayName: 'Breaking Point',
    difficulty: 'Hard',
    baseXp: 81000,
    energyCost: 63,
    gemsFirstClear: 670,
    startingMoney: 800,
    moneyAccrualPerSec: 42.5,
    baseHp: 90,
    enemyBaseHp: 5400,
    spawnScript: [
      { enemyId: 'titan', statMultiplier: 1.3, spawnDelayMs: 1500 },
      { enemyId: 'guardian', statMultiplier: 1.6, spawnDelayMs: 3500 },
      { enemyId: 'sniper', statMultiplier: 2, spawnDelayMs: 5500 },
      { enemyId: 'support', statMultiplier: 2, spawnDelayMs: 7500 },
      { enemyId: 'titan', statMultiplier: 1.4, spawnDelayMs: 10000 },
      { enemyId: 'swarm', statMultiplier: 2, spawnDelayMs: 12000 },
      { enemyId: 'guardian', statMultiplier: 1.6, spawnDelayMs: 14000 },
      { enemyId: 'titan', statMultiplier: 1.4, spawnDelayMs: 16500 },
    ],
  },
  {
    id: 'stage27',
    saga: 'saga3',
    displayName: 'Scorched Line',
    difficulty: 'Hard',
    baseXp: 91000,
    energyCost: 67,
    gemsFirstClear: 730,
    startingMoney: 800,
    moneyAccrualPerSec: 42.5,
    baseHp: 90,
    enemyBaseHp: 6000,
    spawnScript: [
      { enemyId: 'aoe', statMultiplier: 2, spawnDelayMs: 1500 },
      { enemyId: 'titan', statMultiplier: 1.4, spawnDelayMs: 3500 },
      { enemyId: 'support', statMultiplier: 2.1, spawnDelayMs: 6000 },
      { enemyId: 'sniper', statMultiplier: 2.1, spawnDelayMs: 8000 },
      { enemyId: 'guardian', statMultiplier: 1.7, spawnDelayMs: 10500 },
      { enemyId: 'titan', statMultiplier: 1.5, spawnDelayMs: 13000 },
      { enemyId: 'aoe', statMultiplier: 2.1, spawnDelayMs: 15500 },
      { enemyId: 'titan', statMultiplier: 1.5, spawnDelayMs: 18000 },
    ],
  },
  {
    id: 'stage28',
    saga: 'saga3',
    displayName: 'Last Bastion',
    difficulty: 'Hard',
    baseXp: 102000,
    energyCost: 71,
    gemsFirstClear: 800,
    startingMoney: 800,
    moneyAccrualPerSec: 42.5,
    baseHp: 90,
    enemyBaseHp: 6700,
    spawnScript: [
      { enemyId: 'guardian', statMultiplier: 1.8, spawnDelayMs: 1500 },
      { enemyId: 'titan', statMultiplier: 1.5, spawnDelayMs: 3500 },
      { enemyId: 'sniper', statMultiplier: 2.2, spawnDelayMs: 6000 },
      { enemyId: 'support', statMultiplier: 2.2, spawnDelayMs: 8000 },
      { enemyId: 'titan', statMultiplier: 1.6, spawnDelayMs: 10500 },
      { enemyId: 'guardian', statMultiplier: 1.8, spawnDelayMs: 13000 },
      { enemyId: 'swarm', statMultiplier: 2.2, spawnDelayMs: 15000 },
      { enemyId: 'titan', statMultiplier: 1.6, spawnDelayMs: 17000 },
      { enemyId: 'tank', statMultiplier: 2.1, spawnDelayMs: 19000 },
    ],
  },
  {
    id: 'stage29',
    saga: 'saga3',
    displayName: 'Endgame Approach',
    difficulty: 'Hard',
    baseXp: 115000,
    energyCost: 75,
    gemsFirstClear: 880,
    startingMoney: 800,
    moneyAccrualPerSec: 42.5,
    baseHp: 90,
    restrictions: { maxDeployed: 5 },
    enemyBaseHp: 7500,
    spawnScript: [
      { enemyId: 'swarm', statMultiplier: 2.1, spawnDelayMs: 1000 },
      { enemyId: 'sniper', statMultiplier: 2.2, spawnDelayMs: 2600 },
      { enemyId: 'support', statMultiplier: 2.2, spawnDelayMs: 4600 },
      { enemyId: 'tank', statMultiplier: 2.1, spawnDelayMs: 6600 },
      { enemyId: 'guardian', statMultiplier: 1.9, spawnDelayMs: 8800 },
      { enemyId: 'aoe', statMultiplier: 2.2, spawnDelayMs: 11000 },
      { enemyId: 'titan', statMultiplier: 1.7, spawnDelayMs: 13200 },
      { enemyId: 'guardian', statMultiplier: 1.9, spawnDelayMs: 15800 },
      { enemyId: 'titan', statMultiplier: 1.7, spawnDelayMs: 18000 },
      { enemyId: 'sniper', statMultiplier: 2.3, spawnDelayMs: 20200 },
    ],
  },
  {
    id: 'stage30',
    saga: 'saga3',
    displayName: 'The Ascendant',
    difficulty: 'Boss',
    baseXp: 200000,
    energyCost: 90,
    gemsFirstClear: 1500,
    startingMoney: 1000,
    moneyAccrualPerSec: 50,
    baseHp: 100,
    restrictions: { bannedUnitTypes: ['titan'] },
    enemyBaseHp: 15000,
    spawnScript: [
      { enemyId: 'guardian', statMultiplier: 1.9, spawnDelayMs: 1000 },
      { enemyId: 'sniper', statMultiplier: 2.3, spawnDelayMs: 3000 },
      { enemyId: 'support', statMultiplier: 2.3, spawnDelayMs: 5500 },
      { enemyId: 'swarm', statMultiplier: 2.3, spawnDelayMs: 8000 },
      { enemyId: 'titan', statMultiplier: 12, spawnDelayMs: 12000 },
    ],
  },
];
