// Stage roster: 10 curated stages. spawnScript is each stage's COMPLETE wave
// list (no more hand-off into an endless/tier-scaled spawner once it's
// exhausted — Endless Mode and its shared spawner were removed; every enemy
// a stage will ever throw at the player is listed explicitly below, matching
// the bible's model of a stage as a finite, scripted encounter — §A.6.5).
// The only way to clear a stage is destroying its enemy base; if every
// scripted enemy is dead and the base isn't, the player just has to keep
// chipping at it with whatever's left on the field.
//
// Each stage:
//   id            stable key, also the localStorage progress key.
//   displayName   reskin hook / stage-select label.
//   difficulty    'Easy' | 'Normal' | 'Hard' | 'Boss' — just a label + the
//                 select-screen's accent color, doesn't affect gameplay math.
//   startingMoney, moneyAccrualPerSec, baseHp
//                 startingMoney doubles as this stage's level-1 Worker Cat
//                 wallet cap and moneyAccrualPerSec as its level-1 income
//                 rate (see MONEY_CONFIG.js's workerCat block and
//                 GameScene's getWalletCap/getMoneyAccrualPerSec — Worker
//                 Cat levels add flat increments on top of these per-stage
//                 baselines). Values are yen, matching Battle Cats' real
//                 "start each stage with 1000" convention (Easy 1.2x,
//                 Normal 1x, Hard 0.8x, Boss 1x of that base for
//                 startingMoney; moneyAccrualPerSec uses the same ratios
//                 except Hard, which is 0.85x rather than 0.8x — every Hard
//                 stage's moneyAccrualPerSec is consistently 42.5, i.e.
//                 0.85 * the 50 baseline, not 40).
//   enemyBaseHp   the enemy tower's max HP — independent of baseHp (the
//                 player's own base) so it can climb with the difficulty
//                 curve instead of following the player-forgiveness curve.
//                 No fixed cap; scale it however high a stage calls for.
//   spawnScript   ordered, fixed list of enemies — no randomness, no
//                 tier-based auto-scaling. Each entry:
//                   enemyId          key into ENEMY_CONFIG.js
//                   statMultiplier   multiplies that enemy's base hp only
//                                    (1 = unscaled; the stage 10 boss uses 8)
//                   spawnDelayMs     time since the STAGE STARTED (not since
//                                    the previous spawn) — so entries must be
//                                    listed in increasing spawnDelayMs order.
//                                    Mutually exclusive with baseHpPercentTrigger
//                                    below — an entry uses exactly one trigger.
//                   baseHpPercentTrigger (bible §A.3.9) — an alternative to
//                                    spawnDelayMs: fires once the enemy
//                                    base's remaining HP crosses at/below
//                                    this percent, checked in GameScene's
//                                    damageEnemyBase rather than on a timer
//                                    (a failsafe there guarantees this can't
//                                    be skipped by one huge burst). Every
//                                    boss entry in this file uses 99, per
//                                    the bible's "bosses conventionally
//                                    trigger at 99% enemy base HP" note.
//                   isBoss           triggers GameScene's boss-shockwave
//                                    moment (knocks back every deployed
//                                    player unit) the instant this entry
//                                    spawns.
//   baseXp        this stage's XP reward (bible §A.5.1) on a first clear;
//                 repeat clears taper toward a floor — see GameScene's
//                 getXpReward for the exact decay formula. This is the
//                 meta-progression XP (PlayerProgress.js), unrelated to
//                 the in-battle money economy above.
//   energyCost    stamina/Energy (bible §A.9, JP-confirmed term 統率力) spent
//                 to ENTER this stage at all — deducted (and entry blocked
//                 if insufficient) by StageSelectScene before GameScene ever
//                 starts; see Energy.js. Never refunded on a loss.
//   gemsFirstClear  a one-time Gems reward (bible §A.5's premium-currency
//                 equivalent) paid out ONLY the very first time this stage
//                 is won — distinct from the always-available XP/Treasure
//                 rewards above. See GameScene.winStage.
//   restrictions  optional (bible §A.6.5's Restriction Stage) — a modifier
//                 layer most stages omit entirely. Fields (any combo):
//                   maxDeployed       hard cap on simultaneously-alive
//                                     player units on the field at once
//                                     (well below the engine's implicit
//                                     "however many you can afford" limit).
//                   bannedUnitTypes   UNIT_CONFIG keys that can't be
//                                     deployed at all on this stage, even
//                                     though they're still in the Formation.
//                   costRange         { min, max } — a unit can't be
//                                     deployed unless its cost falls in
//                                     this (inclusive) band.
//                 All enforced in GameScene.trySpawnUnit, which shows a
//                 brief on-screen reason when a restriction blocks a tap.
//   allowContinue  optional, defaults to true — bible §A.3.9's Continue
//                 mechanic (pay Gems to refill your base and keep fighting
//                 after a loss) is offered on any stage that doesn't set
//                 this to false. Every saga boss disables it.
//   Clearing a stage = reducing its enemy base's HP to 0 (see GameScene's
//   damageEnemyBase/winStage).

// Saga 1 — the REAL Empire of Cats Chapter 1, all 48 stages, driven by the
// user's updated guide's actual per-stage table (battlecats-db-sourced):
// real prefecture names/order, real energy cost/XP/castle HP/max-deployed
// per stage, real enemy roster per stage (Chapter 1 uses a flat 100%
// strength magnification on every single enemy across all 48 stages — see
// the guide's own note: "第1章は敵の強さ倍率が全ステージ100%" — difficulty
// comes entirely from castle HP/stage composition/max-deployed, never from
// scaling numbers up, which is why every statMultiplier below is 1), and
// the real stage-48 (Iriomote Island) final boss, Kaoru-kun.
//
// Per-enemy spawn TIMING (spawnDelayMs) is NOT real data for 47 of the 48
// stages — the guide gives one fully-detailed worked example (stage 35,
// Tokyo) and confirms enemies appear in the same order they're listed for
// every stage, but doesn't include real first-appearance/repeat-interval
// frame data for the other 47. Generated via tools/gen_saga1_stages.py:
// each stage's real enemy list (in its real order) gets staggered
// ~2.6s apart with one repeat wave per type, ending on whichever enemy the
// real data lists last — this engine's existing scheduleTrickleWave
// fallback then keeps THAT one coming once the scripted list runs out,
// approximating the real game's per-enemy "無制限" (unlimited) repeats.
// A scripted boss (real per-stage data) still spawns via the real
// baseHpPercentTrigger: 99 convention.
//
// startingMoney/moneyAccrualPerSec use the guide's own real numbers
// directly: 6000 is the real, screenshot-confirmed Worker Cat Lv1 wallet
// cap (see MONEY_CONFIG.js's own header), and 170/sec is the guide's stated
// real Lv1 income rate (Chapter 08) — both held constant across all 48
// stages, matching how the real game keeps your OWN economy flat and
// scales difficulty through the enemies a stage throws at you instead.
// Player baseHp is likewise held constant (account-wide Base HP upgrade in
// real Battle Cats, never a per-stage value) rather than invented per stage.
export const STAGE_CONFIG = [

  {
    id: 'stage1',
    saga: 'saga1',
    displayName: 'Nagasaki',
    difficulty: 'Easy',
    baseXp: 1000,
    energyCost: 5,
    gemsFirstClear: 35,
    startingMoney: 6000,
    moneyAccrualPerSec: 170,
    baseHp: 1000,
    restrictions: { maxDeployed: 3 },
    enemyBaseHp: 1000,
    spawnScript: [
      { enemyId: 'basic', statMultiplier: 1, spawnDelayMs: 1500 },
      { enemyId: 'basic', statMultiplier: 1, spawnDelayMs: 2800 },
      { enemyId: 'kanban', statMultiplier: 1, spawnDelayMs: 4100 },
    ],
  },
  {
    id: 'stage2',
    saga: 'saga1',
    displayName: 'Saga',
    difficulty: 'Easy',
    baseXp: 1300,
    energyCost: 5,
    gemsFirstClear: 50,
    startingMoney: 6000,
    moneyAccrualPerSec: 170,
    baseHp: 1000,
    restrictions: { maxDeployed: 4 },
    enemyBaseHp: 1000,
    spawnScript: [
      { enemyId: 'basic', statMultiplier: 1, spawnDelayMs: 1500 },
      { enemyId: 'basic', statMultiplier: 1, spawnDelayMs: 2800 },
      { enemyId: 'fast', statMultiplier: 1, spawnDelayMs: 4100 },
      { enemyId: 'fast', statMultiplier: 1, spawnDelayMs: 5400 },
      { enemyId: 'kanban', statMultiplier: 1, spawnDelayMs: 6700 },
    ],
  },
  {
    id: 'stage3',
    saga: 'saga1',
    displayName: 'Kagoshima',
    difficulty: 'Easy',
    baseXp: 1600,
    energyCost: 8,
    gemsFirstClear: 65,
    startingMoney: 6000,
    moneyAccrualPerSec: 170,
    baseHp: 1000,
    restrictions: { maxDeployed: 5 },
    enemyBaseHp: 1000,
    spawnScript: [
      { enemyId: 'basic', statMultiplier: 1, spawnDelayMs: 1500 },
      { enemyId: 'basic', statMultiplier: 1, spawnDelayMs: 2800 },
      { enemyId: 'fast', statMultiplier: 1, spawnDelayMs: 4100 },
      { enemyId: 'fast', statMultiplier: 1, spawnDelayMs: 5400 },
      { enemyId: 'kanban', statMultiplier: 1, spawnDelayMs: 6700 },
    ],
  },
  {
    id: 'stage4',
    saga: 'saga1',
    displayName: 'Kumamoto',
    difficulty: 'Easy',
    baseXp: 1900,
    energyCost: 8,
    gemsFirstClear: 80,
    startingMoney: 6000,
    moneyAccrualPerSec: 170,
    baseHp: 1000,
    restrictions: { maxDeployed: 5 },
    enemyBaseHp: 1000,
    spawnScript: [
      { enemyId: 'basic', statMultiplier: 1, spawnDelayMs: 1500 },
      { enemyId: 'basic', statMultiplier: 1, spawnDelayMs: 2800 },
      { enemyId: 'fast', statMultiplier: 1, spawnDelayMs: 4100 },
      { enemyId: 'fast', statMultiplier: 1, spawnDelayMs: 5400 },
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 6700 },
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 8000 },
      { enemyId: 'kanban', statMultiplier: 1, spawnDelayMs: 9300 },
    ],
  },
  {
    id: 'stage5',
    saga: 'saga1',
    displayName: 'Miyazaki',
    difficulty: 'Easy',
    baseXp: 2200,
    energyCost: 10,
    gemsFirstClear: 95,
    startingMoney: 6000,
    moneyAccrualPerSec: 170,
    baseHp: 1000,
    restrictions: { maxDeployed: 6 },
    enemyBaseHp: 1500,
    spawnScript: [
      { enemyId: 'basic', statMultiplier: 1, spawnDelayMs: 1500 },
      { enemyId: 'basic', statMultiplier: 1, spawnDelayMs: 2800 },
      { enemyId: 'fast', statMultiplier: 1, spawnDelayMs: 4100 },
      { enemyId: 'fast', statMultiplier: 1, spawnDelayMs: 5400 },
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 6700 },
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 8000 },
      { enemyId: 'kanban', statMultiplier: 1, spawnDelayMs: 9300 },
    ],
  },
  {
    id: 'stage6',
    saga: 'saga1',
    displayName: 'Oita',
    difficulty: 'Easy',
    baseXp: 2500,
    energyCost: 10,
    gemsFirstClear: 110,
    startingMoney: 6000,
    moneyAccrualPerSec: 170,
    baseHp: 1000,
    restrictions: { maxDeployed: 7 },
    enemyBaseHp: 1500,
    spawnScript: [
      { enemyId: 'basic', statMultiplier: 1, spawnDelayMs: 1500 },
      { enemyId: 'basic', statMultiplier: 1, spawnDelayMs: 2800 },
      { enemyId: 'fast', statMultiplier: 1, spawnDelayMs: 4100 },
      { enemyId: 'fast', statMultiplier: 1, spawnDelayMs: 5400 },
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 6700 },
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 8000 },
      { enemyId: 'kanban', statMultiplier: 1, spawnDelayMs: 9300 },
    ],
  },
  {
    id: 'stage7',
    saga: 'saga1',
    displayName: 'Fukuoka',
    difficulty: 'Boss',
    baseXp: 2800,
    energyCost: 16,
    gemsFirstClear: 125,
    startingMoney: 6000,
    moneyAccrualPerSec: 170,
    baseHp: 1000,
    restrictions: { maxDeployed: 6 },
    enemyBaseHp: 2400,
    spawnScript: [
      { enemyId: 'basic', statMultiplier: 1, spawnDelayMs: 1500 },
      { enemyId: 'basic', statMultiplier: 1, spawnDelayMs: 2800 },
      { enemyId: 'fast', statMultiplier: 1, spawnDelayMs: 4100 },
      { enemyId: 'fast', statMultiplier: 1, spawnDelayMs: 5400 },
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 6700 },
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 8000 },
      { enemyId: 'kanban', statMultiplier: 1, spawnDelayMs: 9300 },
      { enemyId: 'tank', statMultiplier: 1, baseHpPercentTrigger: 99, isBoss: true },
    ],
  },
  {
    id: 'stage8',
    saga: 'saga1',
    displayName: 'Kochi',
    difficulty: 'Easy',
    baseXp: 3100,
    energyCost: 12,
    gemsFirstClear: 140,
    startingMoney: 6000,
    moneyAccrualPerSec: 170,
    baseHp: 1000,
    restrictions: { maxDeployed: 5 },
    enemyBaseHp: 1500,
    spawnScript: [
      { enemyId: 'basic', statMultiplier: 1, spawnDelayMs: 1500 },
      { enemyId: 'basic', statMultiplier: 1, spawnDelayMs: 2800 },
      { enemyId: 'fast', statMultiplier: 1, spawnDelayMs: 4100 },
      { enemyId: 'fast', statMultiplier: 1, spawnDelayMs: 5400 },
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 6700 },
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 8000 },
      { enemyId: 'kanban', statMultiplier: 1, spawnDelayMs: 9300 },
    ],
  },
  {
    id: 'stage9',
    saga: 'saga1',
    displayName: 'Ehime',
    difficulty: 'Easy',
    baseXp: 3400,
    energyCost: 12,
    gemsFirstClear: 155,
    startingMoney: 6000,
    moneyAccrualPerSec: 170,
    baseHp: 1000,
    restrictions: { maxDeployed: 10 },
    enemyBaseHp: 3000,
    spawnScript: [
      { enemyId: 'basic', statMultiplier: 1, spawnDelayMs: 1500 },
      { enemyId: 'basic', statMultiplier: 1, spawnDelayMs: 2800 },
      { enemyId: 'fast', statMultiplier: 1, spawnDelayMs: 4100 },
      { enemyId: 'fast', statMultiplier: 1, spawnDelayMs: 5400 },
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 6700 },
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 8000 },
      { enemyId: 'kanban', statMultiplier: 1, spawnDelayMs: 9300 },
    ],
  },
  {
    id: 'stage10',
    saga: 'saga1',
    displayName: 'Tokushima',
    difficulty: 'Boss',
    baseXp: 3700,
    energyCost: 14,
    gemsFirstClear: 170,
    startingMoney: 6000,
    moneyAccrualPerSec: 170,
    baseHp: 1000,
    restrictions: { maxDeployed: 5 },
    enemyBaseHp: 2500,
    spawnScript: [
      { enemyId: 'basic', statMultiplier: 1, spawnDelayMs: 1500 },
      { enemyId: 'basic', statMultiplier: 1, spawnDelayMs: 2800 },
      { enemyId: 'fast', statMultiplier: 1, spawnDelayMs: 4100 },
      { enemyId: 'fast', statMultiplier: 1, spawnDelayMs: 5400 },
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 6700 },
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 8000 },
      { enemyId: 'kanban', statMultiplier: 1, spawnDelayMs: 9300 },
      { enemyId: 'aoe', statMultiplier: 1, baseHpPercentTrigger: 99, isBoss: true },
    ],
  },
  {
    id: 'stage11',
    saga: 'saga1',
    displayName: 'Kagawa',
    difficulty: 'Easy',
    baseXp: 4000,
    energyCost: 18,
    gemsFirstClear: 185,
    startingMoney: 6000,
    moneyAccrualPerSec: 170,
    baseHp: 1000,
    restrictions: { maxDeployed: 6 },
    enemyBaseHp: 3500,
    spawnScript: [
      { enemyId: 'basic', statMultiplier: 1, spawnDelayMs: 1500 },
      { enemyId: 'basic', statMultiplier: 1, spawnDelayMs: 2800 },
      { enemyId: 'fast', statMultiplier: 1, spawnDelayMs: 4100 },
      { enemyId: 'fast', statMultiplier: 1, spawnDelayMs: 5400 },
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 6700 },
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 8000 },
      { enemyId: 'tank', statMultiplier: 1, spawnDelayMs: 9300 },
      { enemyId: 'tank', statMultiplier: 1, spawnDelayMs: 10600 },
      { enemyId: 'kanban', statMultiplier: 1, spawnDelayMs: 11900 },
    ],
  },
  {
    id: 'stage12',
    saga: 'saga1',
    displayName: 'Yamaguchi',
    difficulty: 'Easy',
    baseXp: 4300,
    energyCost: 20,
    gemsFirstClear: 200,
    startingMoney: 6000,
    moneyAccrualPerSec: 170,
    baseHp: 1000,
    restrictions: { maxDeployed: 7 },
    enemyBaseHp: 4000,
    spawnScript: [
      { enemyId: 'basic', statMultiplier: 1, spawnDelayMs: 1500 },
      { enemyId: 'basic', statMultiplier: 1, spawnDelayMs: 2800 },
      { enemyId: 'fast', statMultiplier: 1, spawnDelayMs: 4100 },
      { enemyId: 'fast', statMultiplier: 1, spawnDelayMs: 5400 },
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 6700 },
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 8000 },
      { enemyId: 'aoe', statMultiplier: 1, spawnDelayMs: 9300 },
      { enemyId: 'aoe', statMultiplier: 1, spawnDelayMs: 10600 },
      { enemyId: 'kanban', statMultiplier: 1, spawnDelayMs: 11900 },
    ],
  },
  {
    id: 'stage13',
    saga: 'saga1',
    displayName: 'Hiroshima',
    difficulty: 'Easy',
    baseXp: 4600,
    energyCost: 18,
    gemsFirstClear: 215,
    startingMoney: 6000,
    moneyAccrualPerSec: 170,
    baseHp: 1000,
    restrictions: { maxDeployed: 12 },
    enemyBaseHp: 5000,
    spawnScript: [
      { enemyId: 'basic', statMultiplier: 1, spawnDelayMs: 1500 },
      { enemyId: 'basic', statMultiplier: 1, spawnDelayMs: 2800 },
      { enemyId: 'fast', statMultiplier: 1, spawnDelayMs: 4100 },
      { enemyId: 'fast', statMultiplier: 1, spawnDelayMs: 5400 },
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 6700 },
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 8000 },
      { enemyId: 'sniper', statMultiplier: 1, spawnDelayMs: 9300 },
      { enemyId: 'sniper', statMultiplier: 1, spawnDelayMs: 10600 },
      { enemyId: 'kanban', statMultiplier: 1, spawnDelayMs: 11900 },
    ],
  },
  {
    id: 'stage14',
    saga: 'saga1',
    displayName: 'Shimane',
    difficulty: 'Normal',
    baseXp: 4900,
    energyCost: 20,
    gemsFirstClear: 230,
    startingMoney: 6000,
    moneyAccrualPerSec: 170,
    baseHp: 1000,
    restrictions: { maxDeployed: 3 },
    enemyBaseHp: 6000,
    spawnScript: [
      { enemyId: 'basic', statMultiplier: 1, spawnDelayMs: 1500 },
      { enemyId: 'basic', statMultiplier: 1, spawnDelayMs: 2800 },
      { enemyId: 'fast', statMultiplier: 1, spawnDelayMs: 4100 },
      { enemyId: 'fast', statMultiplier: 1, spawnDelayMs: 5400 },
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 6700 },
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 8000 },
      { enemyId: 'tank', statMultiplier: 1, spawnDelayMs: 9300 },
      { enemyId: 'tank', statMultiplier: 1, spawnDelayMs: 10600 },
      { enemyId: 'kanban', statMultiplier: 1, spawnDelayMs: 11900 },
    ],
  },
  {
    id: 'stage15',
    saga: 'saga1',
    displayName: 'Okayama',
    difficulty: 'Normal',
    baseXp: 5200,
    energyCost: 24,
    gemsFirstClear: 245,
    startingMoney: 6000,
    moneyAccrualPerSec: 170,
    baseHp: 1000,
    restrictions: { maxDeployed: 4 },
    enemyBaseHp: 6100,
    spawnScript: [
      { enemyId: 'basic', statMultiplier: 1, spawnDelayMs: 1500 },
      { enemyId: 'basic', statMultiplier: 1, spawnDelayMs: 2800 },
      { enemyId: 'fast', statMultiplier: 1, spawnDelayMs: 4100 },
      { enemyId: 'fast', statMultiplier: 1, spawnDelayMs: 5400 },
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 6700 },
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 8000 },
      { enemyId: 'tank', statMultiplier: 1, spawnDelayMs: 9300 },
      { enemyId: 'tank', statMultiplier: 1, spawnDelayMs: 10600 },
      { enemyId: 'aoe', statMultiplier: 1, spawnDelayMs: 11900 },
      { enemyId: 'aoe', statMultiplier: 1, spawnDelayMs: 13200 },
      { enemyId: 'kanban', statMultiplier: 1, spawnDelayMs: 14500 },
    ],
  },
  {
    id: 'stage16',
    saga: 'saga1',
    displayName: 'Tottori',
    difficulty: 'Boss',
    baseXp: 5500,
    energyCost: 26,
    gemsFirstClear: 260,
    startingMoney: 6000,
    moneyAccrualPerSec: 170,
    baseHp: 1000,
    restrictions: { maxDeployed: 6 },
    enemyBaseHp: 7000,
    spawnScript: [
      { enemyId: 'basic', statMultiplier: 1, spawnDelayMs: 1500 },
      { enemyId: 'basic', statMultiplier: 1, spawnDelayMs: 2800 },
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 4100 },
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 5400 },
      { enemyId: 'kanban', statMultiplier: 1, spawnDelayMs: 6700 },
      { enemyId: 'gory', statMultiplier: 1, baseHpPercentTrigger: 99, isBoss: true },
    ],
  },
  {
    id: 'stage17',
    saga: 'saga1',
    displayName: 'Hyogo',
    difficulty: 'Normal',
    baseXp: 5800,
    energyCost: 20,
    gemsFirstClear: 275,
    startingMoney: 6000,
    moneyAccrualPerSec: 170,
    baseHp: 1000,
    restrictions: { maxDeployed: 10 },
    enemyBaseHp: 7000,
    spawnScript: [
      { enemyId: 'basic', statMultiplier: 1, spawnDelayMs: 1500 },
      { enemyId: 'basic', statMultiplier: 1, spawnDelayMs: 2800 },
      { enemyId: 'fast', statMultiplier: 1, spawnDelayMs: 4100 },
      { enemyId: 'fast', statMultiplier: 1, spawnDelayMs: 5400 },
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 6700 },
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 8000 },
      { enemyId: 'tank', statMultiplier: 1, spawnDelayMs: 9300 },
      { enemyId: 'tank', statMultiplier: 1, spawnDelayMs: 10600 },
      { enemyId: 'aoe', statMultiplier: 1, spawnDelayMs: 11900 },
      { enemyId: 'aoe', statMultiplier: 1, spawnDelayMs: 13200 },
      { enemyId: 'sniper', statMultiplier: 1, spawnDelayMs: 14500 },
      { enemyId: 'sniper', statMultiplier: 1, spawnDelayMs: 15800 },
      { enemyId: 'kanban', statMultiplier: 1, spawnDelayMs: 17100 },
    ],
  },
  {
    id: 'stage18',
    saga: 'saga1',
    displayName: 'Wakayama',
    difficulty: 'Normal',
    baseXp: 6100,
    energyCost: 24,
    gemsFirstClear: 290,
    startingMoney: 6000,
    moneyAccrualPerSec: 170,
    baseHp: 1000,
    restrictions: { maxDeployed: 10 },
    enemyBaseHp: 8000,
    spawnScript: [
      { enemyId: 'basic', statMultiplier: 1, spawnDelayMs: 1500 },
      { enemyId: 'basic', statMultiplier: 1, spawnDelayMs: 2800 },
      { enemyId: 'fast', statMultiplier: 1, spawnDelayMs: 4100 },
      { enemyId: 'fast', statMultiplier: 1, spawnDelayMs: 5400 },
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 6700 },
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 8000 },
      { enemyId: 'aoe', statMultiplier: 1, spawnDelayMs: 9300 },
      { enemyId: 'aoe', statMultiplier: 1, spawnDelayMs: 10600 },
      { enemyId: 'sniper', statMultiplier: 1, spawnDelayMs: 11900 },
      { enemyId: 'sniper', statMultiplier: 1, spawnDelayMs: 13200 },
      { enemyId: 'kanban', statMultiplier: 1, spawnDelayMs: 14500 },
    ],
  },
  {
    id: 'stage19',
    saga: 'saga1',
    displayName: 'Osaka',
    difficulty: 'Normal',
    baseXp: 6400,
    energyCost: 28,
    gemsFirstClear: 305,
    startingMoney: 6000,
    moneyAccrualPerSec: 170,
    baseHp: 1000,
    restrictions: { maxDeployed: 10 },
    enemyBaseHp: 9000,
    spawnScript: [
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 1500 },
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 2800 },
      { enemyId: 'gory', statMultiplier: 1, spawnDelayMs: 4100 },
      { enemyId: 'gory', statMultiplier: 1, spawnDelayMs: 5400 },
      { enemyId: 'mehmeh', statMultiplier: 1, spawnDelayMs: 6700 },
      { enemyId: 'mehmeh', statMultiplier: 1, spawnDelayMs: 8000 },
      { enemyId: 'kanban', statMultiplier: 1, spawnDelayMs: 9300 },
    ],
  },
  {
    id: 'stage20',
    saga: 'saga1',
    displayName: 'Kyoto',
    difficulty: 'Normal',
    baseXp: 6700,
    energyCost: 30,
    gemsFirstClear: 320,
    startingMoney: 6000,
    moneyAccrualPerSec: 170,
    baseHp: 1000,
    restrictions: { maxDeployed: 10 },
    enemyBaseHp: 9000,
    spawnScript: [
      { enemyId: 'basic', statMultiplier: 1, spawnDelayMs: 1500 },
      { enemyId: 'basic', statMultiplier: 1, spawnDelayMs: 2800 },
      { enemyId: 'fast', statMultiplier: 1, spawnDelayMs: 4100 },
      { enemyId: 'fast', statMultiplier: 1, spawnDelayMs: 5400 },
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 6700 },
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 8000 },
      { enemyId: 'tank', statMultiplier: 1, spawnDelayMs: 9300 },
      { enemyId: 'tank', statMultiplier: 1, spawnDelayMs: 10600 },
      { enemyId: 'aoe', statMultiplier: 1, spawnDelayMs: 11900 },
      { enemyId: 'aoe', statMultiplier: 1, spawnDelayMs: 13200 },
      { enemyId: 'gory', statMultiplier: 1, spawnDelayMs: 14500 },
      { enemyId: 'gory', statMultiplier: 1, spawnDelayMs: 15800 },
      { enemyId: 'mehmeh', statMultiplier: 1, spawnDelayMs: 17100 },
      { enemyId: 'mehmeh', statMultiplier: 1, spawnDelayMs: 18400 },
      { enemyId: 'kanban', statMultiplier: 1, spawnDelayMs: 19700 },
    ],
  },
  {
    id: 'stage21',
    saga: 'saga1',
    displayName: 'Nara',
    difficulty: 'Normal',
    baseXp: 7000,
    energyCost: 24,
    gemsFirstClear: 335,
    startingMoney: 6000,
    moneyAccrualPerSec: 170,
    baseHp: 1000,
    restrictions: { maxDeployed: 10 },
    enemyBaseHp: 10000,
    spawnScript: [
      { enemyId: 'basic', statMultiplier: 1, spawnDelayMs: 1500 },
      { enemyId: 'basic', statMultiplier: 1, spawnDelayMs: 2800 },
      { enemyId: 'fast', statMultiplier: 1, spawnDelayMs: 4100 },
      { enemyId: 'fast', statMultiplier: 1, spawnDelayMs: 5400 },
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 6700 },
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 8000 },
      { enemyId: 'tank', statMultiplier: 1, spawnDelayMs: 9300 },
      { enemyId: 'tank', statMultiplier: 1, spawnDelayMs: 10600 },
      { enemyId: 'aoe', statMultiplier: 1, spawnDelayMs: 11900 },
      { enemyId: 'aoe', statMultiplier: 1, spawnDelayMs: 13200 },
      { enemyId: 'sniper', statMultiplier: 1, spawnDelayMs: 14500 },
      { enemyId: 'sniper', statMultiplier: 1, spawnDelayMs: 15800 },
      { enemyId: 'gory', statMultiplier: 1, spawnDelayMs: 17100 },
      { enemyId: 'gory', statMultiplier: 1, spawnDelayMs: 18400 },
      { enemyId: 'mehmeh', statMultiplier: 1, spawnDelayMs: 19700 },
      { enemyId: 'mehmeh', statMultiplier: 1, spawnDelayMs: 21000 },
      { enemyId: 'kanban', statMultiplier: 1, spawnDelayMs: 22300 },
    ],
  },
  {
    id: 'stage22',
    saga: 'saga1',
    displayName: 'Mie',
    difficulty: 'Normal',
    baseXp: 7300,
    energyCost: 28,
    gemsFirstClear: 350,
    startingMoney: 6000,
    moneyAccrualPerSec: 170,
    baseHp: 1000,
    restrictions: { maxDeployed: 4 },
    enemyBaseHp: 12000,
    spawnScript: [
      { enemyId: 'fast', statMultiplier: 1, spawnDelayMs: 1500 },
      { enemyId: 'fast', statMultiplier: 1, spawnDelayMs: 2800 },
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 4100 },
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 5400 },
      { enemyId: 'sniper', statMultiplier: 1, spawnDelayMs: 6700 },
      { enemyId: 'sniper', statMultiplier: 1, spawnDelayMs: 8000 },
      { enemyId: 'gory', statMultiplier: 1, spawnDelayMs: 9300 },
      { enemyId: 'gory', statMultiplier: 1, spawnDelayMs: 10600 },
      { enemyId: 'mehmeh', statMultiplier: 1, spawnDelayMs: 11900 },
      { enemyId: 'mehmeh', statMultiplier: 1, spawnDelayMs: 13200 },
      { enemyId: 'kanban', statMultiplier: 1, spawnDelayMs: 14500 },
    ],
  },
  {
    id: 'stage23',
    saga: 'saga1',
    displayName: 'Shiga',
    difficulty: 'Boss',
    baseXp: 7600,
    energyCost: 32,
    gemsFirstClear: 365,
    startingMoney: 6000,
    moneyAccrualPerSec: 170,
    baseHp: 1000,
    restrictions: { maxDeployed: 5 },
    enemyBaseHp: 15000,
    spawnScript: [
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 1500 },
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 2800 },
      { enemyId: 'aoe', statMultiplier: 1, spawnDelayMs: 4100 },
      { enemyId: 'aoe', statMultiplier: 1, spawnDelayMs: 5400 },
      { enemyId: 'kanban', statMultiplier: 1, spawnDelayMs: 6700 },
      { enemyId: 'support', statMultiplier: 1, baseHpPercentTrigger: 99, isBoss: true },
    ],
  },
  {
    id: 'stage24',
    saga: 'saga1',
    displayName: 'Fukui',
    difficulty: 'Normal',
    baseXp: 7900,
    energyCost: 40,
    gemsFirstClear: 380,
    startingMoney: 6000,
    moneyAccrualPerSec: 170,
    baseHp: 1000,
    restrictions: { maxDeployed: 3 },
    enemyBaseHp: 15000,
    spawnScript: [
      { enemyId: 'tank', statMultiplier: 1, spawnDelayMs: 1500 },
      { enemyId: 'tank', statMultiplier: 1, spawnDelayMs: 2800 },
      { enemyId: 'aoe', statMultiplier: 1, spawnDelayMs: 4100 },
      { enemyId: 'aoe', statMultiplier: 1, spawnDelayMs: 5400 },
      { enemyId: 'sniper', statMultiplier: 1, spawnDelayMs: 6700 },
      { enemyId: 'sniper', statMultiplier: 1, spawnDelayMs: 8000 },
      { enemyId: 'gory', statMultiplier: 1, spawnDelayMs: 9300 },
      { enemyId: 'gory', statMultiplier: 1, spawnDelayMs: 10600 },
      { enemyId: 'kanban', statMultiplier: 1, spawnDelayMs: 11900 },
    ],
  },
  {
    id: 'stage25',
    saga: 'saga1',
    displayName: 'Ishikawa',
    difficulty: 'Normal',
    baseXp: 8200,
    energyCost: 25,
    gemsFirstClear: 395,
    startingMoney: 6000,
    moneyAccrualPerSec: 170,
    baseHp: 1000,
    restrictions: { maxDeployed: 5 },
    enemyBaseHp: 15000,
    spawnScript: [
      { enemyId: 'basic', statMultiplier: 1, spawnDelayMs: 1500 },
      { enemyId: 'basic', statMultiplier: 1, spawnDelayMs: 2800 },
      { enemyId: 'fast', statMultiplier: 1, spawnDelayMs: 4100 },
      { enemyId: 'fast', statMultiplier: 1, spawnDelayMs: 5400 },
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 6700 },
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 8000 },
      { enemyId: 'tank', statMultiplier: 1, spawnDelayMs: 9300 },
      { enemyId: 'tank', statMultiplier: 1, spawnDelayMs: 10600 },
      { enemyId: 'sniper', statMultiplier: 1, spawnDelayMs: 11900 },
      { enemyId: 'sniper', statMultiplier: 1, spawnDelayMs: 13200 },
      { enemyId: 'mehmeh', statMultiplier: 1, spawnDelayMs: 14500 },
      { enemyId: 'mehmeh', statMultiplier: 1, spawnDelayMs: 15800 },
      { enemyId: 'kanban', statMultiplier: 1, spawnDelayMs: 17100 },
    ],
  },
  {
    id: 'stage26',
    saga: 'saga1',
    displayName: 'Aichi',
    difficulty: 'Normal',
    baseXp: 8500,
    energyCost: 30,
    gemsFirstClear: 410,
    startingMoney: 6000,
    moneyAccrualPerSec: 170,
    baseHp: 1000,
    enemyBaseHp: 15000,
    spawnScript: [
      { enemyId: 'support', statMultiplier: 1, spawnDelayMs: 1500 },
      { enemyId: 'support', statMultiplier: 1, spawnDelayMs: 2800 },
      { enemyId: 'wanikun', statMultiplier: 1, spawnDelayMs: 4100 },
      { enemyId: 'wanikun', statMultiplier: 1, spawnDelayMs: 5400 },
      { enemyId: 'kanban', statMultiplier: 1, spawnDelayMs: 6700 },
    ],
  },
  {
    id: 'stage27',
    saga: 'saga1',
    displayName: 'Gifu',
    difficulty: 'Normal',
    baseXp: 8800,
    energyCost: 32,
    gemsFirstClear: 425,
    startingMoney: 6000,
    moneyAccrualPerSec: 170,
    baseHp: 1000,
    restrictions: { maxDeployed: 8 },
    enemyBaseHp: 15000,
    spawnScript: [
      { enemyId: 'basic', statMultiplier: 1, spawnDelayMs: 1500 },
      { enemyId: 'basic', statMultiplier: 1, spawnDelayMs: 2800 },
      { enemyId: 'fast', statMultiplier: 1, spawnDelayMs: 4100 },
      { enemyId: 'fast', statMultiplier: 1, spawnDelayMs: 5400 },
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 6700 },
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 8000 },
      { enemyId: 'gory', statMultiplier: 1, spawnDelayMs: 9300 },
      { enemyId: 'gory', statMultiplier: 1, spawnDelayMs: 10600 },
      { enemyId: 'mehmeh', statMultiplier: 1, spawnDelayMs: 11900 },
      { enemyId: 'mehmeh', statMultiplier: 1, spawnDelayMs: 13200 },
      { enemyId: 'support', statMultiplier: 1, spawnDelayMs: 14500 },
      { enemyId: 'support', statMultiplier: 1, spawnDelayMs: 15800 },
      { enemyId: 'wanikun', statMultiplier: 1, spawnDelayMs: 17100 },
      { enemyId: 'wanikun', statMultiplier: 1, spawnDelayMs: 18400 },
      { enemyId: 'kanban', statMultiplier: 1, spawnDelayMs: 19700 },
    ],
  },
  {
    id: 'stage28',
    saga: 'saga1',
    displayName: 'Toyama',
    difficulty: 'Normal',
    baseXp: 9100,
    energyCost: 36,
    gemsFirstClear: 440,
    startingMoney: 6000,
    moneyAccrualPerSec: 170,
    baseHp: 1000,
    restrictions: { maxDeployed: 8 },
    enemyBaseHp: 15000,
    spawnScript: [
      { enemyId: 'basic', statMultiplier: 1, spawnDelayMs: 1500 },
      { enemyId: 'basic', statMultiplier: 1, spawnDelayMs: 2800 },
      { enemyId: 'fast', statMultiplier: 1, spawnDelayMs: 4100 },
      { enemyId: 'fast', statMultiplier: 1, spawnDelayMs: 5400 },
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 6700 },
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 8000 },
      { enemyId: 'tank', statMultiplier: 1, spawnDelayMs: 9300 },
      { enemyId: 'tank', statMultiplier: 1, spawnDelayMs: 10600 },
      { enemyId: 'aoe', statMultiplier: 1, spawnDelayMs: 11900 },
      { enemyId: 'aoe', statMultiplier: 1, spawnDelayMs: 13200 },
      { enemyId: 'sniper', statMultiplier: 1, spawnDelayMs: 14500 },
      { enemyId: 'sniper', statMultiplier: 1, spawnDelayMs: 15800 },
      { enemyId: 'gory', statMultiplier: 1, spawnDelayMs: 17100 },
      { enemyId: 'gory', statMultiplier: 1, spawnDelayMs: 18400 },
      { enemyId: 'support', statMultiplier: 1, spawnDelayMs: 19700 },
      { enemyId: 'support', statMultiplier: 1, spawnDelayMs: 21000 },
      { enemyId: 'wanikun', statMultiplier: 1, spawnDelayMs: 22300 },
      { enemyId: 'wanikun', statMultiplier: 1, spawnDelayMs: 23600 },
      { enemyId: 'kanban', statMultiplier: 1, spawnDelayMs: 24900 },
    ],
  },
  {
    id: 'stage29',
    saga: 'saga1',
    displayName: 'Shizuoka',
    difficulty: 'Boss',
    baseXp: 9400,
    energyCost: 40,
    gemsFirstClear: 455,
    startingMoney: 6000,
    moneyAccrualPerSec: 170,
    baseHp: 1000,
    restrictions: { maxDeployed: 10 },
    enemyBaseHp: 18000,
    spawnScript: [
      { enemyId: 'basic', statMultiplier: 1, spawnDelayMs: 1500 },
      { enemyId: 'basic', statMultiplier: 1, spawnDelayMs: 2800 },
      { enemyId: 'fast', statMultiplier: 1, spawnDelayMs: 4100 },
      { enemyId: 'fast', statMultiplier: 1, spawnDelayMs: 5400 },
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 6700 },
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 8000 },
      { enemyId: 'wanikun', statMultiplier: 1, spawnDelayMs: 9300 },
      { enemyId: 'wanikun', statMultiplier: 1, spawnDelayMs: 10600 },
      { enemyId: 'kanban', statMultiplier: 1, spawnDelayMs: 11900 },
      { enemyId: 'ranged', statMultiplier: 1, baseHpPercentTrigger: 99, isBoss: true },
    ],
  },
  {
    id: 'stage30',
    saga: 'saga1',
    displayName: 'Yamanashi',
    difficulty: 'Normal',
    baseXp: 9700,
    energyCost: 24,
    gemsFirstClear: 470,
    startingMoney: 6000,
    moneyAccrualPerSec: 170,
    baseHp: 1000,
    restrictions: { maxDeployed: 10 },
    enemyBaseHp: 15000,
    spawnScript: [
      { enemyId: 'fast', statMultiplier: 1, spawnDelayMs: 1500 },
      { enemyId: 'fast', statMultiplier: 1, spawnDelayMs: 2800 },
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 4100 },
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 5400 },
      { enemyId: 'tank', statMultiplier: 1, spawnDelayMs: 6700 },
      { enemyId: 'tank', statMultiplier: 1, spawnDelayMs: 8000 },
      { enemyId: 'aoe', statMultiplier: 1, spawnDelayMs: 9300 },
      { enemyId: 'aoe', statMultiplier: 1, spawnDelayMs: 10600 },
      { enemyId: 'sniper', statMultiplier: 1, spawnDelayMs: 11900 },
      { enemyId: 'sniper', statMultiplier: 1, spawnDelayMs: 13200 },
      { enemyId: 'gory', statMultiplier: 1, spawnDelayMs: 14500 },
      { enemyId: 'gory', statMultiplier: 1, spawnDelayMs: 15800 },
      { enemyId: 'mehmeh', statMultiplier: 1, spawnDelayMs: 17100 },
      { enemyId: 'mehmeh', statMultiplier: 1, spawnDelayMs: 18400 },
      { enemyId: 'support', statMultiplier: 1, spawnDelayMs: 19700 },
      { enemyId: 'support', statMultiplier: 1, spawnDelayMs: 21000 },
      { enemyId: 'wanikun', statMultiplier: 1, spawnDelayMs: 22300 },
      { enemyId: 'wanikun', statMultiplier: 1, spawnDelayMs: 23600 },
      { enemyId: 'kanban', statMultiplier: 1, spawnDelayMs: 24900 },
    ],
  },
  {
    id: 'stage31',
    saga: 'saga1',
    displayName: 'Nagano',
    difficulty: 'Normal',
    baseXp: 10000,
    energyCost: 26,
    gemsFirstClear: 485,
    startingMoney: 6000,
    moneyAccrualPerSec: 170,
    baseHp: 1000,
    restrictions: { maxDeployed: 10 },
    enemyBaseHp: 8000,
    spawnScript: [
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 1500 },
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 2800 },
      { enemyId: 'aoe', statMultiplier: 1, spawnDelayMs: 4100 },
      { enemyId: 'aoe', statMultiplier: 1, spawnDelayMs: 5400 },
      { enemyId: 'mehmeh', statMultiplier: 1, spawnDelayMs: 6700 },
      { enemyId: 'mehmeh', statMultiplier: 1, spawnDelayMs: 8000 },
      { enemyId: 'ranged', statMultiplier: 1, spawnDelayMs: 9300 },
      { enemyId: 'ranged', statMultiplier: 1, spawnDelayMs: 10600 },
      { enemyId: 'wanikun', statMultiplier: 1, spawnDelayMs: 11900 },
      { enemyId: 'wanikun', statMultiplier: 1, spawnDelayMs: 13200 },
      { enemyId: 'kanban', statMultiplier: 1, spawnDelayMs: 14500 },
    ],
  },
  {
    id: 'stage32',
    saga: 'saga1',
    displayName: 'Niigata',
    difficulty: 'Normal',
    baseXp: 10300,
    energyCost: 30,
    gemsFirstClear: 500,
    startingMoney: 6000,
    moneyAccrualPerSec: 170,
    baseHp: 1000,
    restrictions: { maxDeployed: 8 },
    enemyBaseHp: 18000,
    spawnScript: [
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 1500 },
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 2800 },
      { enemyId: 'aoe', statMultiplier: 1, spawnDelayMs: 4100 },
      { enemyId: 'aoe', statMultiplier: 1, spawnDelayMs: 5400 },
      { enemyId: 'support', statMultiplier: 1, spawnDelayMs: 6700 },
      { enemyId: 'support', statMultiplier: 1, spawnDelayMs: 8000 },
      { enemyId: 'usagin', statMultiplier: 1, spawnDelayMs: 9300 },
      { enemyId: 'usagin', statMultiplier: 1, spawnDelayMs: 10600 },
      { enemyId: 'kanban', statMultiplier: 1, spawnDelayMs: 11900 },
    ],
  },
  {
    id: 'stage33',
    saga: 'saga1',
    displayName: 'Kanagawa',
    difficulty: 'Normal',
    baseXp: 10600,
    energyCost: 35,
    gemsFirstClear: 515,
    startingMoney: 6000,
    moneyAccrualPerSec: 170,
    baseHp: 1000,
    restrictions: { maxDeployed: 6 },
    enemyBaseHp: 18000,
    spawnScript: [
      { enemyId: 'fast', statMultiplier: 1, spawnDelayMs: 1500 },
      { enemyId: 'fast', statMultiplier: 1, spawnDelayMs: 2800 },
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 4100 },
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 5400 },
      { enemyId: 'tank', statMultiplier: 1, spawnDelayMs: 6700 },
      { enemyId: 'tank', statMultiplier: 1, spawnDelayMs: 8000 },
      { enemyId: 'aoe', statMultiplier: 1, spawnDelayMs: 9300 },
      { enemyId: 'aoe', statMultiplier: 1, spawnDelayMs: 10600 },
      { enemyId: 'sniper', statMultiplier: 1, spawnDelayMs: 11900 },
      { enemyId: 'sniper', statMultiplier: 1, spawnDelayMs: 13200 },
      { enemyId: 'gory', statMultiplier: 1, spawnDelayMs: 14500 },
      { enemyId: 'gory', statMultiplier: 1, spawnDelayMs: 15800 },
      { enemyId: 'mehmeh', statMultiplier: 1, spawnDelayMs: 17100 },
      { enemyId: 'mehmeh', statMultiplier: 1, spawnDelayMs: 18400 },
      { enemyId: 'support', statMultiplier: 1, spawnDelayMs: 19700 },
      { enemyId: 'support', statMultiplier: 1, spawnDelayMs: 21000 },
      { enemyId: 'wanikun', statMultiplier: 1, spawnDelayMs: 22300 },
      { enemyId: 'wanikun', statMultiplier: 1, spawnDelayMs: 23600 },
      { enemyId: 'kanban', statMultiplier: 1, spawnDelayMs: 24900 },
    ],
  },
  {
    id: 'stage34',
    saga: 'saga1',
    displayName: 'Chiba',
    difficulty: 'Normal',
    baseXp: 10900,
    energyCost: 28,
    gemsFirstClear: 530,
    startingMoney: 6000,
    moneyAccrualPerSec: 170,
    baseHp: 1000,
    restrictions: { maxDeployed: 10 },
    enemyBaseHp: 18000,
    spawnScript: [
      { enemyId: 'fast', statMultiplier: 1, spawnDelayMs: 1500 },
      { enemyId: 'fast', statMultiplier: 1, spawnDelayMs: 2800 },
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 4100 },
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 5400 },
      { enemyId: 'tank', statMultiplier: 1, spawnDelayMs: 6700 },
      { enemyId: 'tank', statMultiplier: 1, spawnDelayMs: 8000 },
      { enemyId: 'aoe', statMultiplier: 1, spawnDelayMs: 9300 },
      { enemyId: 'aoe', statMultiplier: 1, spawnDelayMs: 10600 },
      { enemyId: 'sniper', statMultiplier: 1, spawnDelayMs: 11900 },
      { enemyId: 'sniper', statMultiplier: 1, spawnDelayMs: 13200 },
      { enemyId: 'gory', statMultiplier: 1, spawnDelayMs: 14500 },
      { enemyId: 'gory', statMultiplier: 1, spawnDelayMs: 15800 },
      { enemyId: 'mehmeh', statMultiplier: 1, spawnDelayMs: 17100 },
      { enemyId: 'mehmeh', statMultiplier: 1, spawnDelayMs: 18400 },
      { enemyId: 'support', statMultiplier: 1, spawnDelayMs: 19700 },
      { enemyId: 'support', statMultiplier: 1, spawnDelayMs: 21000 },
      { enemyId: 'wanikun', statMultiplier: 1, spawnDelayMs: 22300 },
      { enemyId: 'wanikun', statMultiplier: 1, spawnDelayMs: 23600 },
      { enemyId: 'kanban', statMultiplier: 1, spawnDelayMs: 24900 },
    ],
  },
  {
    id: 'stage35',
    saga: 'saga1',
    displayName: 'Tokyo',
    difficulty: 'Boss',
    baseXp: 11200,
    energyCost: 30,
    gemsFirstClear: 545,
    startingMoney: 6000,
    moneyAccrualPerSec: 170,
    baseHp: 1000,
    restrictions: { maxDeployed: 10 },
    enemyBaseHp: 20000,
    spawnScript: [
      { enemyId: 'basic', statMultiplier: 1, spawnDelayMs: 1500 },
      { enemyId: 'basic', statMultiplier: 1, spawnDelayMs: 2800 },
      { enemyId: 'fast', statMultiplier: 1, spawnDelayMs: 4100 },
      { enemyId: 'fast', statMultiplier: 1, spawnDelayMs: 5400 },
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 6700 },
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 8000 },
      { enemyId: 'wanikun', statMultiplier: 1, spawnDelayMs: 9300 },
      { enemyId: 'wanikun', statMultiplier: 1, spawnDelayMs: 10600 },
      { enemyId: 'usagin', statMultiplier: 1, spawnDelayMs: 11900 },
      { enemyId: 'usagin', statMultiplier: 1, spawnDelayMs: 13200 },
      { enemyId: 'kanban', statMultiplier: 1, spawnDelayMs: 14500 },
      { enemyId: 'kangaroo', statMultiplier: 1, baseHpPercentTrigger: 99, isBoss: true },
    ],
  },
  {
    id: 'stage36',
    saga: 'saga1',
    displayName: 'Saitama',
    difficulty: 'Normal',
    baseXp: 11500,
    energyCost: 40,
    gemsFirstClear: 560,
    startingMoney: 6000,
    moneyAccrualPerSec: 170,
    baseHp: 1000,
    restrictions: { maxDeployed: 10 },
    enemyBaseHp: 20000,
    spawnScript: [
      { enemyId: 'basic', statMultiplier: 1, spawnDelayMs: 1500 },
      { enemyId: 'basic', statMultiplier: 1, spawnDelayMs: 2800 },
      { enemyId: 'fast', statMultiplier: 1, spawnDelayMs: 4100 },
      { enemyId: 'fast', statMultiplier: 1, spawnDelayMs: 5400 },
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 6700 },
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 8000 },
      { enemyId: 'tank', statMultiplier: 1, spawnDelayMs: 9300 },
      { enemyId: 'tank', statMultiplier: 1, spawnDelayMs: 10600 },
      { enemyId: 'aoe', statMultiplier: 1, spawnDelayMs: 11900 },
      { enemyId: 'aoe', statMultiplier: 1, spawnDelayMs: 13200 },
      { enemyId: 'mehmeh', statMultiplier: 1, spawnDelayMs: 14500 },
      { enemyId: 'mehmeh', statMultiplier: 1, spawnDelayMs: 15800 },
      { enemyId: 'ranged', statMultiplier: 1, spawnDelayMs: 17100 },
      { enemyId: 'ranged', statMultiplier: 1, spawnDelayMs: 18400 },
      { enemyId: 'wanikun', statMultiplier: 1, spawnDelayMs: 19700 },
      { enemyId: 'wanikun', statMultiplier: 1, spawnDelayMs: 21000 },
      { enemyId: 'usagin', statMultiplier: 1, spawnDelayMs: 22300 },
      { enemyId: 'usagin', statMultiplier: 1, spawnDelayMs: 23600 },
      { enemyId: 'kanban', statMultiplier: 1, spawnDelayMs: 24900 },
    ],
  },
  {
    id: 'stage37',
    saga: 'saga1',
    displayName: 'Gunma',
    difficulty: 'Hard',
    baseXp: 11800,
    energyCost: 30,
    gemsFirstClear: 575,
    startingMoney: 6000,
    moneyAccrualPerSec: 170,
    baseHp: 1000,
    restrictions: { maxDeployed: 4 },
    enemyBaseHp: 20000,
    spawnScript: [
      { enemyId: 'basic', statMultiplier: 1, spawnDelayMs: 1500 },
      { enemyId: 'basic', statMultiplier: 1, spawnDelayMs: 2800 },
      { enemyId: 'fast', statMultiplier: 1, spawnDelayMs: 4100 },
      { enemyId: 'fast', statMultiplier: 1, spawnDelayMs: 5400 },
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 6700 },
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 8000 },
      { enemyId: 'tank', statMultiplier: 1, spawnDelayMs: 9300 },
      { enemyId: 'tank', statMultiplier: 1, spawnDelayMs: 10600 },
      { enemyId: 'aoe', statMultiplier: 1, spawnDelayMs: 11900 },
      { enemyId: 'aoe', statMultiplier: 1, spawnDelayMs: 13200 },
      { enemyId: 'mehmeh', statMultiplier: 1, spawnDelayMs: 14500 },
      { enemyId: 'mehmeh', statMultiplier: 1, spawnDelayMs: 15800 },
      { enemyId: 'kangaroo', statMultiplier: 1, spawnDelayMs: 17100 },
      { enemyId: 'kangaroo', statMultiplier: 1, spawnDelayMs: 18400 },
      { enemyId: 'wanikun', statMultiplier: 1, spawnDelayMs: 19700 },
      { enemyId: 'wanikun', statMultiplier: 1, spawnDelayMs: 21000 },
      { enemyId: 'usagin', statMultiplier: 1, spawnDelayMs: 22300 },
      { enemyId: 'usagin', statMultiplier: 1, spawnDelayMs: 23600 },
      { enemyId: 'kanban', statMultiplier: 1, spawnDelayMs: 24900 },
    ],
  },
  {
    id: 'stage38',
    saga: 'saga1',
    displayName: 'Tochigi',
    difficulty: 'Boss',
    baseXp: 12100,
    energyCost: 35,
    gemsFirstClear: 590,
    startingMoney: 6000,
    moneyAccrualPerSec: 170,
    baseHp: 1000,
    restrictions: { maxDeployed: 8 },
    enemyBaseHp: 20000,
    spawnScript: [
      { enemyId: 'basic', statMultiplier: 1, spawnDelayMs: 1500 },
      { enemyId: 'basic', statMultiplier: 1, spawnDelayMs: 2800 },
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 4100 },
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 5400 },
      { enemyId: 'gory', statMultiplier: 1, spawnDelayMs: 6700 },
      { enemyId: 'gory', statMultiplier: 1, spawnDelayMs: 8000 },
      { enemyId: 'wanikun', statMultiplier: 1, spawnDelayMs: 9300 },
      { enemyId: 'wanikun', statMultiplier: 1, spawnDelayMs: 10600 },
      { enemyId: 'swarm', statMultiplier: 1, spawnDelayMs: 11900 },
      { enemyId: 'swarm', statMultiplier: 1, spawnDelayMs: 13200 },
      { enemyId: 'kanban', statMultiplier: 1, spawnDelayMs: 14500 },
      { enemyId: 'gagagaga', statMultiplier: 1, baseHpPercentTrigger: 99, isBoss: true },
    ],
  },
  {
    id: 'stage39',
    saga: 'saga1',
    displayName: 'Ibaraki',
    difficulty: 'Normal',
    baseXp: 12400,
    energyCost: 40,
    gemsFirstClear: 605,
    startingMoney: 6000,
    moneyAccrualPerSec: 170,
    baseHp: 1000,
    restrictions: { maxDeployed: 5 },
    enemyBaseHp: 20000,
    spawnScript: [
      { enemyId: 'basic', statMultiplier: 1, spawnDelayMs: 1500 },
      { enemyId: 'basic', statMultiplier: 1, spawnDelayMs: 2800 },
      { enemyId: 'fast', statMultiplier: 1, spawnDelayMs: 4100 },
      { enemyId: 'fast', statMultiplier: 1, spawnDelayMs: 5400 },
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 6700 },
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 8000 },
      { enemyId: 'sniper', statMultiplier: 1, spawnDelayMs: 9300 },
      { enemyId: 'sniper', statMultiplier: 1, spawnDelayMs: 10600 },
      { enemyId: 'gory', statMultiplier: 1, spawnDelayMs: 11900 },
      { enemyId: 'gory', statMultiplier: 1, spawnDelayMs: 13200 },
      { enemyId: 'support', statMultiplier: 1, spawnDelayMs: 14500 },
      { enemyId: 'support', statMultiplier: 1, spawnDelayMs: 15800 },
      { enemyId: 'swarm', statMultiplier: 1, spawnDelayMs: 17100 },
      { enemyId: 'swarm', statMultiplier: 1, spawnDelayMs: 18400 },
      { enemyId: 'kanban', statMultiplier: 1, spawnDelayMs: 19700 },
    ],
  },
  {
    id: 'stage40',
    saga: 'saga1',
    displayName: 'Fukushima',
    difficulty: 'Normal',
    baseXp: 12700,
    energyCost: 30,
    gemsFirstClear: 620,
    startingMoney: 6000,
    moneyAccrualPerSec: 170,
    baseHp: 1000,
    restrictions: { maxDeployed: 10 },
    enemyBaseHp: 20000,
    spawnScript: [
      { enemyId: 'basic', statMultiplier: 1, spawnDelayMs: 1500 },
      { enemyId: 'basic', statMultiplier: 1, spawnDelayMs: 2800 },
      { enemyId: 'fast', statMultiplier: 1, spawnDelayMs: 4100 },
      { enemyId: 'fast', statMultiplier: 1, spawnDelayMs: 5400 },
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 6700 },
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 8000 },
      { enemyId: 'sniper', statMultiplier: 1, spawnDelayMs: 9300 },
      { enemyId: 'sniper', statMultiplier: 1, spawnDelayMs: 10600 },
      { enemyId: 'gory', statMultiplier: 1, spawnDelayMs: 11900 },
      { enemyId: 'gory', statMultiplier: 1, spawnDelayMs: 13200 },
      { enemyId: 'support', statMultiplier: 1, spawnDelayMs: 14500 },
      { enemyId: 'support', statMultiplier: 1, spawnDelayMs: 15800 },
      { enemyId: 'ranged', statMultiplier: 1, spawnDelayMs: 17100 },
      { enemyId: 'ranged', statMultiplier: 1, spawnDelayMs: 18400 },
      { enemyId: 'kangaroo', statMultiplier: 1, spawnDelayMs: 19700 },
      { enemyId: 'kangaroo', statMultiplier: 1, spawnDelayMs: 21000 },
      { enemyId: 'swarm', statMultiplier: 1, spawnDelayMs: 22300 },
      { enemyId: 'swarm', statMultiplier: 1, spawnDelayMs: 23600 },
      { enemyId: 'kanban', statMultiplier: 1, spawnDelayMs: 24900 },
    ],
  },
  {
    id: 'stage41',
    saga: 'saga1',
    displayName: 'Miyagi',
    difficulty: 'Boss',
    baseXp: 13000,
    energyCost: 32,
    gemsFirstClear: 635,
    startingMoney: 6000,
    moneyAccrualPerSec: 170,
    baseHp: 1000,
    restrictions: { maxDeployed: 10 },
    enemyBaseHp: 20000,
    spawnScript: [
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 1500 },
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 2800 },
      { enemyId: 'wanikun', statMultiplier: 1, spawnDelayMs: 4100 },
      { enemyId: 'wanikun', statMultiplier: 1, spawnDelayMs: 5400 },
      { enemyId: 'swarm', statMultiplier: 1, spawnDelayMs: 6700 },
      { enemyId: 'swarm', statMultiplier: 1, spawnDelayMs: 8000 },
      { enemyId: 'kanban', statMultiplier: 1, spawnDelayMs: 9300 },
      { enemyId: 'ikkaku', statMultiplier: 1, baseHpPercentTrigger: 99, isBoss: true },
    ],
  },
  {
    id: 'stage42',
    saga: 'saga1',
    displayName: 'Yamagata',
    difficulty: 'Hard',
    baseXp: 13300,
    energyCost: 35,
    gemsFirstClear: 650,
    startingMoney: 6000,
    moneyAccrualPerSec: 170,
    baseHp: 1000,
    restrictions: { maxDeployed: 5 },
    enemyBaseHp: 25000,
    spawnScript: [
      { enemyId: 'basic', statMultiplier: 1, spawnDelayMs: 1500 },
      { enemyId: 'basic', statMultiplier: 1, spawnDelayMs: 2800 },
      { enemyId: 'fast', statMultiplier: 1, spawnDelayMs: 4100 },
      { enemyId: 'fast', statMultiplier: 1, spawnDelayMs: 5400 },
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 6700 },
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 8000 },
      { enemyId: 'sniper', statMultiplier: 1, spawnDelayMs: 9300 },
      { enemyId: 'sniper', statMultiplier: 1, spawnDelayMs: 10600 },
      { enemyId: 'gory', statMultiplier: 1, spawnDelayMs: 11900 },
      { enemyId: 'gory', statMultiplier: 1, spawnDelayMs: 13200 },
      { enemyId: 'support', statMultiplier: 1, spawnDelayMs: 14500 },
      { enemyId: 'support', statMultiplier: 1, spawnDelayMs: 15800 },
      { enemyId: 'ranged', statMultiplier: 1, spawnDelayMs: 17100 },
      { enemyId: 'ranged', statMultiplier: 1, spawnDelayMs: 18400 },
      { enemyId: 'kangaroo', statMultiplier: 1, spawnDelayMs: 19700 },
      { enemyId: 'kangaroo', statMultiplier: 1, spawnDelayMs: 21000 },
      { enemyId: 'swarm', statMultiplier: 1, spawnDelayMs: 22300 },
      { enemyId: 'swarm', statMultiplier: 1, spawnDelayMs: 23600 },
      { enemyId: 'kanban', statMultiplier: 1, spawnDelayMs: 24900 },
    ],
  },
  {
    id: 'stage43',
    saga: 'saga1',
    displayName: 'Iwate',
    difficulty: 'Normal',
    baseXp: 13600,
    energyCost: 30,
    gemsFirstClear: 665,
    startingMoney: 6000,
    moneyAccrualPerSec: 170,
    baseHp: 1000,
    restrictions: { maxDeployed: 10 },
    enemyBaseHp: 20000,
    spawnScript: [
      { enemyId: 'basic', statMultiplier: 1, spawnDelayMs: 1500 },
      { enemyId: 'basic', statMultiplier: 1, spawnDelayMs: 2800 },
      { enemyId: 'fast', statMultiplier: 1, spawnDelayMs: 4100 },
      { enemyId: 'fast', statMultiplier: 1, spawnDelayMs: 5400 },
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 6700 },
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 8000 },
      { enemyId: 'aoe', statMultiplier: 1, spawnDelayMs: 9300 },
      { enemyId: 'aoe', statMultiplier: 1, spawnDelayMs: 10600 },
      { enemyId: 'support', statMultiplier: 1, spawnDelayMs: 11900 },
      { enemyId: 'support', statMultiplier: 1, spawnDelayMs: 13200 },
      { enemyId: 'ikkaku', statMultiplier: 1, spawnDelayMs: 14500 },
      { enemyId: 'ikkaku', statMultiplier: 1, spawnDelayMs: 15800 },
      { enemyId: 'wanikun', statMultiplier: 1, spawnDelayMs: 17100 },
      { enemyId: 'wanikun', statMultiplier: 1, spawnDelayMs: 18400 },
      { enemyId: 'usagin', statMultiplier: 1, spawnDelayMs: 19700 },
      { enemyId: 'usagin', statMultiplier: 1, spawnDelayMs: 21000 },
      { enemyId: 'kanban', statMultiplier: 1, spawnDelayMs: 22300 },
    ],
  },
  {
    id: 'stage44',
    saga: 'saga1',
    displayName: 'Akita',
    difficulty: 'Boss',
    baseXp: 13900,
    energyCost: 32,
    gemsFirstClear: 680,
    startingMoney: 6000,
    moneyAccrualPerSec: 170,
    baseHp: 1000,
    restrictions: { maxDeployed: 4 },
    enemyBaseHp: 25000,
    spawnScript: [
      { enemyId: 'basic', statMultiplier: 1, spawnDelayMs: 1500 },
      { enemyId: 'basic', statMultiplier: 1, spawnDelayMs: 2800 },
      { enemyId: 'fast', statMultiplier: 1, spawnDelayMs: 4100 },
      { enemyId: 'fast', statMultiplier: 1, spawnDelayMs: 5400 },
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 6700 },
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 8000 },
      { enemyId: 'swarm', statMultiplier: 1, spawnDelayMs: 9300 },
      { enemyId: 'swarm', statMultiplier: 1, spawnDelayMs: 10600 },
      { enemyId: 'kanban', statMultiplier: 1, spawnDelayMs: 11900 },
      { enemyId: 'guardian', statMultiplier: 1, baseHpPercentTrigger: 99, isBoss: true },
    ],
  },
  {
    id: 'stage45',
    saga: 'saga1',
    displayName: 'Aomori',
    difficulty: 'Hard',
    baseXp: 14200,
    energyCost: 40,
    gemsFirstClear: 695,
    startingMoney: 6000,
    moneyAccrualPerSec: 170,
    baseHp: 1000,
    restrictions: { maxDeployed: 2 },
    enemyBaseHp: 20000,
    spawnScript: [
      { enemyId: 'tank', statMultiplier: 1, spawnDelayMs: 1500 },
      { enemyId: 'tank', statMultiplier: 1, spawnDelayMs: 2800 },
      { enemyId: 'aoe', statMultiplier: 1, spawnDelayMs: 4100 },
      { enemyId: 'aoe', statMultiplier: 1, spawnDelayMs: 5400 },
      { enemyId: 'sniper', statMultiplier: 1, spawnDelayMs: 6700 },
      { enemyId: 'sniper', statMultiplier: 1, spawnDelayMs: 8000 },
      { enemyId: 'gory', statMultiplier: 1, spawnDelayMs: 9300 },
      { enemyId: 'gory', statMultiplier: 1, spawnDelayMs: 10600 },
      { enemyId: 'support', statMultiplier: 1, spawnDelayMs: 11900 },
      { enemyId: 'support', statMultiplier: 1, spawnDelayMs: 13200 },
      { enemyId: 'ranged', statMultiplier: 1, spawnDelayMs: 14500 },
      { enemyId: 'ranged', statMultiplier: 1, spawnDelayMs: 15800 },
      { enemyId: 'kangaroo', statMultiplier: 1, spawnDelayMs: 17100 },
      { enemyId: 'kangaroo', statMultiplier: 1, spawnDelayMs: 18400 },
      { enemyId: 'kanban', statMultiplier: 1, spawnDelayMs: 19700 },
    ],
  },
  {
    id: 'stage46',
    saga: 'saga1',
    displayName: 'Hokkaido',
    difficulty: 'Normal',
    baseXp: 14500,
    energyCost: 50,
    gemsFirstClear: 710,
    startingMoney: 6000,
    moneyAccrualPerSec: 170,
    baseHp: 1000,
    restrictions: { maxDeployed: 10 },
    enemyBaseHp: 20000,
    spawnScript: [
      { enemyId: 'aoe', statMultiplier: 1, spawnDelayMs: 1500 },
      { enemyId: 'aoe', statMultiplier: 1, spawnDelayMs: 2800 },
      { enemyId: 'guardian', statMultiplier: 1, spawnDelayMs: 4100 },
      { enemyId: 'guardian', statMultiplier: 1, spawnDelayMs: 5400 },
      { enemyId: 'usagin', statMultiplier: 1, spawnDelayMs: 6700 },
      { enemyId: 'usagin', statMultiplier: 1, spawnDelayMs: 8000 },
      { enemyId: 'swarm', statMultiplier: 1, spawnDelayMs: 9300 },
      { enemyId: 'swarm', statMultiplier: 1, spawnDelayMs: 10600 },
      { enemyId: 'gagagaga', statMultiplier: 1, spawnDelayMs: 11900 },
      { enemyId: 'gagagaga', statMultiplier: 1, spawnDelayMs: 13200 },
      { enemyId: 'kanban', statMultiplier: 1, spawnDelayMs: 14500 },
    ],
  },
  {
    id: 'stage47',
    saga: 'saga1',
    displayName: 'Okinawa',
    difficulty: 'Hard',
    baseXp: 14800,
    energyCost: 50,
    gemsFirstClear: 725,
    startingMoney: 6000,
    moneyAccrualPerSec: 170,
    baseHp: 1000,
    restrictions: { maxDeployed: 3 },
    enemyBaseHp: 30000,
    spawnScript: [
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 1500 },
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 2800 },
      { enemyId: 'tank', statMultiplier: 1, spawnDelayMs: 4100 },
      { enemyId: 'tank', statMultiplier: 1, spawnDelayMs: 5400 },
      { enemyId: 'sniper', statMultiplier: 1, spawnDelayMs: 6700 },
      { enemyId: 'sniper', statMultiplier: 1, spawnDelayMs: 8000 },
      { enemyId: 'gory', statMultiplier: 1, spawnDelayMs: 9300 },
      { enemyId: 'gory', statMultiplier: 1, spawnDelayMs: 10600 },
      { enemyId: 'support', statMultiplier: 1, spawnDelayMs: 11900 },
      { enemyId: 'support', statMultiplier: 1, spawnDelayMs: 13200 },
      { enemyId: 'ranged', statMultiplier: 1, spawnDelayMs: 14500 },
      { enemyId: 'ranged', statMultiplier: 1, spawnDelayMs: 15800 },
      { enemyId: 'kangaroo', statMultiplier: 1, spawnDelayMs: 17100 },
      { enemyId: 'kangaroo', statMultiplier: 1, spawnDelayMs: 18400 },
      { enemyId: 'ikkaku', statMultiplier: 1, spawnDelayMs: 19700 },
      { enemyId: 'ikkaku', statMultiplier: 1, spawnDelayMs: 21000 },
      { enemyId: 'guardian', statMultiplier: 1, spawnDelayMs: 22300 },
      { enemyId: 'guardian', statMultiplier: 1, spawnDelayMs: 23600 },
      { enemyId: 'kanban', statMultiplier: 1, spawnDelayMs: 24900 },
    ],
  },
  {
    id: 'stage48',
    saga: 'saga1',
    displayName: 'Iriomote Island',
    difficulty: 'Boss',
    baseXp: 15100,
    energyCost: 50,
    gemsFirstClear: 740,
    startingMoney: 6000,
    moneyAccrualPerSec: 170,
    baseHp: 1000,
    restrictions: { maxDeployed: 4 },
    enemyBaseHp: 99999,
    spawnScript: [
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 1500 },
      { enemyId: 'thatguy', statMultiplier: 1, spawnDelayMs: 2800 },
      { enemyId: 'tank', statMultiplier: 1, spawnDelayMs: 4100 },
      { enemyId: 'tank', statMultiplier: 1, spawnDelayMs: 5400 },
      { enemyId: 'sniper', statMultiplier: 1, spawnDelayMs: 6700 },
      { enemyId: 'sniper', statMultiplier: 1, spawnDelayMs: 8000 },
      { enemyId: 'gory', statMultiplier: 1, spawnDelayMs: 9300 },
      { enemyId: 'gory', statMultiplier: 1, spawnDelayMs: 10600 },
      { enemyId: 'kangaroo', statMultiplier: 1, spawnDelayMs: 11900 },
      { enemyId: 'kangaroo', statMultiplier: 1, spawnDelayMs: 13200 },
      { enemyId: 'kanban', statMultiplier: 1, spawnDelayMs: 14500 },
      { enemyId: 'titan', statMultiplier: 1, baseHpPercentTrigger: 99, isBoss: true },
    ],
  },

  // Saga 2 & 3 — real Battle Cats repeats the SAME map across Chapters 1-3,
  // just with the enemy strength magnification (statMultiplier) climbing —
  // so these reuse saga1's own 10 real enemies (no zombie/colossus/behemoth;
  // still dormant, see ENEMY_CONFIG.js) at progressively higher %, rather
  // than introducing new enemy types. Economy again held constant
  // (6000¥/170¥-sec, see saga1's own header) — difficulty comes entirely
  // from enemy strength here, matching the real game.
  {
    id: 'stage49',
    saga: 'saga2',
    displayName: 'Empire of Axies: Chapter 2, I',
    difficulty: 'Easy',
    baseXp: 13000,
    energyCost: 26,
    gemsFirstClear: 160,
    startingMoney: 6000,
    moneyAccrualPerSec: 170,
    baseHp: 1000,
    enemyBaseHp: 5000,
    spawnScript: [
      { enemyId: 'basic', statMultiplier: 1.4, spawnDelayMs: 1000 },
      { enemyId: 'swarm', statMultiplier: 1.4, spawnDelayMs: 3000 },
      { enemyId: 'fast', statMultiplier: 1.4, spawnDelayMs: 5500 },
      { enemyId: 'sniper', statMultiplier: 1.4, spawnDelayMs: 8500 },
      { enemyId: 'tank', statMultiplier: 1.4, spawnDelayMs: 12000 },
    ],
  },
  {
    id: 'stage50',
    saga: 'saga2',
    displayName: 'Empire of Axies: Chapter 2, II',
    difficulty: 'Easy',
    baseXp: 14500,
    energyCost: 27,
    gemsFirstClear: 175,
    startingMoney: 6000,
    moneyAccrualPerSec: 170,
    baseHp: 1000,
    enemyBaseHp: 5800,
    spawnScript: [
      { enemyId: 'basic', statMultiplier: 1.45, spawnDelayMs: 1000 },
      { enemyId: 'aoe', statMultiplier: 1.45, spawnDelayMs: 3500 },
      { enemyId: 'support', statMultiplier: 1.45, spawnDelayMs: 6500 },
      { enemyId: 'swarm', statMultiplier: 1.5, spawnDelayMs: 9500 },
      { enemyId: 'tank', statMultiplier: 1.5, spawnDelayMs: 12500 },
      { enemyId: 'sniper', statMultiplier: 1.5, spawnDelayMs: 16000 },
    ],
  },
  {
    id: 'stage51',
    saga: 'saga2',
    displayName: 'Empire of Axies: Chapter 2, III',
    difficulty: 'Normal',
    baseXp: 16500,
    energyCost: 29,
    gemsFirstClear: 195,
    startingMoney: 6000,
    moneyAccrualPerSec: 170,
    baseHp: 950,
    enemyBaseHp: 6700,
    spawnScript: [
      { enemyId: 'fast', statMultiplier: 1.55, spawnDelayMs: 1000 },
      { enemyId: 'sniper', statMultiplier: 1.55, spawnDelayMs: 3500 },
      { enemyId: 'guardian', statMultiplier: 1.5, spawnDelayMs: 6500 },
      { enemyId: 'aoe', statMultiplier: 1.55, spawnDelayMs: 9500 },
      { enemyId: 'tank', statMultiplier: 1.6, spawnDelayMs: 13000 },
      { enemyId: 'support', statMultiplier: 1.55, spawnDelayMs: 16500 },
    ],
  },
  {
    id: 'stage52',
    saga: 'saga2',
    displayName: 'Empire of Axies: Chapter 2, IV',
    difficulty: 'Normal',
    baseXp: 18500,
    energyCost: 31,
    gemsFirstClear: 215,
    startingMoney: 6000,
    moneyAccrualPerSec: 170,
    baseHp: 950,
    enemyBaseHp: 7700,
    spawnScript: [
      { enemyId: 'basic', statMultiplier: 1.6, spawnDelayMs: 1000 },
      { enemyId: 'ranged', statMultiplier: 1.5, spawnDelayMs: 3500 },
      { enemyId: 'aoe', statMultiplier: 1.65, spawnDelayMs: 7000 },
      { enemyId: 'guardian', statMultiplier: 1.6, spawnDelayMs: 10500 },
      { enemyId: 'sniper', statMultiplier: 1.65, spawnDelayMs: 14000 },
      { enemyId: 'support', statMultiplier: 1.65, spawnDelayMs: 17500 },
    ],
  },
  {
    id: 'stage53',
    saga: 'saga2',
    displayName: 'Empire of Axies: Chapter 2, V',
    difficulty: 'Normal',
    baseXp: 21000,
    energyCost: 33,
    gemsFirstClear: 240,
    startingMoney: 6000,
    moneyAccrualPerSec: 170,
    baseHp: 950,
    restrictions: { costRange: { min: 100, max: 1500 } },
    enemyBaseHp: 8800,
    spawnScript: [
      { enemyId: 'basic', statMultiplier: 1.7, spawnDelayMs: 1000 },
      { enemyId: 'fast', statMultiplier: 1.7, spawnDelayMs: 2800 },
      { enemyId: 'tank', statMultiplier: 1.7, spawnDelayMs: 5600 },
      { enemyId: 'sniper', statMultiplier: 1.75, spawnDelayMs: 9000 },
      { enemyId: 'ranged', statMultiplier: 1.6, spawnDelayMs: 12500 },
      { enemyId: 'aoe', statMultiplier: 1.75, spawnDelayMs: 16000 },
      { enemyId: 'support', statMultiplier: 1.75, spawnDelayMs: 19000 },
    ],
  },
  {
    id: 'stage54',
    saga: 'saga2',
    displayName: 'Empire of Axies: Chapter 2, VI',
    difficulty: 'Hard',
    baseXp: 24000,
    energyCost: 36,
    gemsFirstClear: 270,
    startingMoney: 6000,
    moneyAccrualPerSec: 170,
    baseHp: 900,
    enemyBaseHp: 10000,
    spawnScript: [
      { enemyId: 'swarm', statMultiplier: 1.8, spawnDelayMs: 1000 },
      { enemyId: 'guardian', statMultiplier: 1.75, spawnDelayMs: 3500 },
      { enemyId: 'sniper', statMultiplier: 1.85, spawnDelayMs: 7000 },
      { enemyId: 'tank', statMultiplier: 1.85, spawnDelayMs: 10500 },
      { enemyId: 'support', statMultiplier: 1.85, spawnDelayMs: 14000 },
      { enemyId: 'aoe', statMultiplier: 1.85, spawnDelayMs: 17500 },
      { enemyId: 'ranged', statMultiplier: 1.7, spawnDelayMs: 21000 },
    ],
  },
  {
    id: 'stage55',
    saga: 'saga2',
    displayName: 'Empire of Axies: Chapter 2, VII',
    difficulty: 'Hard',
    baseXp: 27000,
    energyCost: 39,
    gemsFirstClear: 300,
    startingMoney: 6000,
    moneyAccrualPerSec: 170,
    baseHp: 900,
    enemyBaseHp: 11400,
    spawnScript: [
      { enemyId: 'basic', statMultiplier: 1.9, spawnDelayMs: 1000 },
      { enemyId: 'fast', statMultiplier: 1.9, spawnDelayMs: 2800 },
      { enemyId: 'aoe', statMultiplier: 1.95, spawnDelayMs: 5600 },
      { enemyId: 'guardian', statMultiplier: 1.85, spawnDelayMs: 9000 },
      { enemyId: 'sniper', statMultiplier: 1.95, spawnDelayMs: 12500 },
      { enemyId: 'tank', statMultiplier: 1.95, spawnDelayMs: 16000 },
      { enemyId: 'support', statMultiplier: 1.95, spawnDelayMs: 19500 },
    ],
  },
  {
    id: 'stage56',
    saga: 'saga2',
    displayName: 'Empire of Axies: Chapter 2, VIII',
    difficulty: 'Hard',
    baseXp: 30500,
    energyCost: 42,
    gemsFirstClear: 335,
    startingMoney: 6000,
    moneyAccrualPerSec: 170,
    baseHp: 900,
    enemyBaseHp: 13000,
    spawnScript: [
      { enemyId: 'swarm', statMultiplier: 2, spawnDelayMs: 1000 },
      { enemyId: 'ranged', statMultiplier: 1.85, spawnDelayMs: 3000 },
      { enemyId: 'guardian', statMultiplier: 1.95, spawnDelayMs: 6000 },
      { enemyId: 'aoe', statMultiplier: 2.05, spawnDelayMs: 9500 },
      { enemyId: 'sniper', statMultiplier: 2.05, spawnDelayMs: 13000 },
      { enemyId: 'tank', statMultiplier: 2.05, spawnDelayMs: 16500 },
      { enemyId: 'support', statMultiplier: 2.05, spawnDelayMs: 20000 },
    ],
  },
  {
    id: 'stage57',
    saga: 'saga2',
    displayName: 'Empire of Axies: Chapter 2, IX',
    difficulty: 'Hard',
    baseXp: 34500,
    energyCost: 45,
    gemsFirstClear: 375,
    startingMoney: 6000,
    moneyAccrualPerSec: 170,
    baseHp: 900,
    // Restriction Stage (bible §A.6.5): full-roster gauntlet before the
    // Chapter 2 boss.
    restrictions: { maxDeployed: 6 },
    enemyBaseHp: 14800,
    spawnScript: [
      { enemyId: 'basic', statMultiplier: 2.1, spawnDelayMs: 800 },
      { enemyId: 'fast', statMultiplier: 2.1, spawnDelayMs: 2400 },
      { enemyId: 'swarm', statMultiplier: 2.15, spawnDelayMs: 4800 },
      { enemyId: 'sniper', statMultiplier: 2.15, spawnDelayMs: 8000 },
      { enemyId: 'tank', statMultiplier: 2.15, spawnDelayMs: 11500 },
      { enemyId: 'aoe', statMultiplier: 2.15, spawnDelayMs: 15000 },
      { enemyId: 'support', statMultiplier: 2.15, spawnDelayMs: 18500 },
      { enemyId: 'guardian', statMultiplier: 2.1, spawnDelayMs: 22000 },
      { enemyId: 'ranged', statMultiplier: 2, spawnDelayMs: 25500 },
    ],
  },
  {
    id: 'stage58',
    saga: 'saga2',
    displayName: 'Empire of Axies: Overlord Returns',
    difficulty: 'Boss',
    baseXp: 60000,
    energyCost: 55,
    gemsFirstClear: 600,
    startingMoney: 6000,
    moneyAccrualPerSec: 170,
    baseHp: 900,
    restrictions: { bannedUnitTypes: ['titan'] },
    allowContinue: false, // Continue (bible §A.3.9) — disabled for saga bosses, see stage10's own comment
    enemyBaseHp: 20000,
    spawnScript: [
      { enemyId: 'sniper', statMultiplier: 2.2, spawnDelayMs: 1000 },
      { enemyId: 'support', statMultiplier: 2.2, spawnDelayMs: 3500 },
      { enemyId: 'swarm', statMultiplier: 2.2, spawnDelayMs: 6500 },
      { enemyId: 'tank', statMultiplier: 2.2, spawnDelayMs: 10000 },
      { enemyId: 'aoe', statMultiplier: 2.2, spawnDelayMs: 14000 },
      { enemyId: 'guardian', statMultiplier: 2.15, spawnDelayMs: 18000 },
      { enemyId: 'ranged', statMultiplier: 2.1, spawnDelayMs: 22000 },
      // Base-HP%-triggered boss spawn (see stage10's own comment) — same
      // 99% trigger + isBoss shockwave. Emperor Nyandam again — real Battle
      // Cats re-fights its own Chapter 1 final boss, stronger, as Chapter
      // 2's finale too.
      { enemyId: 'titan', statMultiplier: 1.6, baseHpPercentTrigger: 99, isBoss: true },
    ],
  },
  {
    id: 'stage59',
    saga: 'saga3',
    displayName: 'Empire of Axies: Chapter 3, I',
    difficulty: 'Easy',
    baseXp: 65000,
    energyCost: 57,
    gemsFirstClear: 640,
    startingMoney: 6000,
    moneyAccrualPerSec: 170,
    baseHp: 1000,
    enemyBaseHp: 22000,
    spawnScript: [
      { enemyId: 'basic', statMultiplier: 2.3, spawnDelayMs: 1000 },
      { enemyId: 'swarm', statMultiplier: 2.3, spawnDelayMs: 3000 },
      { enemyId: 'sniper', statMultiplier: 2.3, spawnDelayMs: 5500 },
      { enemyId: 'tank', statMultiplier: 2.3, spawnDelayMs: 8500 },
      { enemyId: 'support', statMultiplier: 2.3, spawnDelayMs: 12000 },
    ],
  },
  {
    id: 'stage60',
    saga: 'saga3',
    displayName: 'Empire of Axies: Chapter 3, II',
    difficulty: 'Easy',
    baseXp: 72000,
    energyCost: 60,
    gemsFirstClear: 680,
    startingMoney: 6000,
    moneyAccrualPerSec: 170,
    baseHp: 1000,
    enemyBaseHp: 24500,
    spawnScript: [
      { enemyId: 'fast', statMultiplier: 2.4, spawnDelayMs: 1000 },
      { enemyId: 'aoe', statMultiplier: 2.4, spawnDelayMs: 3500 },
      { enemyId: 'guardian', statMultiplier: 2.35, spawnDelayMs: 6500 },
      { enemyId: 'sniper', statMultiplier: 2.45, spawnDelayMs: 10000 },
      { enemyId: 'tank', statMultiplier: 2.45, spawnDelayMs: 13500 },
      { enemyId: 'ranged', statMultiplier: 2.3, spawnDelayMs: 17000 },
    ],
  },
  {
    id: 'stage61',
    saga: 'saga3',
    displayName: 'Empire of Axies: Chapter 3, III',
    difficulty: 'Normal',
    baseXp: 82000,
    energyCost: 63,
    gemsFirstClear: 740,
    startingMoney: 6000,
    moneyAccrualPerSec: 170,
    baseHp: 950,
    enemyBaseHp: 27500,
    spawnScript: [
      { enemyId: 'basic', statMultiplier: 2.55, spawnDelayMs: 1000 },
      { enemyId: 'support', statMultiplier: 2.55, spawnDelayMs: 3500 },
      { enemyId: 'swarm', statMultiplier: 2.6, spawnDelayMs: 7000 },
      { enemyId: 'guardian', statMultiplier: 2.5, spawnDelayMs: 10500 },
      { enemyId: 'aoe', statMultiplier: 2.6, spawnDelayMs: 14000 },
      { enemyId: 'sniper', statMultiplier: 2.65, spawnDelayMs: 17500 },
      { enemyId: 'tank', statMultiplier: 2.65, spawnDelayMs: 21000 },
    ],
  },
  {
    id: 'stage62',
    saga: 'saga3',
    displayName: 'Empire of Axies: Chapter 3, IV',
    difficulty: 'Normal',
    baseXp: 92000,
    energyCost: 67,
    gemsFirstClear: 800,
    startingMoney: 6000,
    moneyAccrualPerSec: 170,
    baseHp: 950,
    enemyBaseHp: 31000,
    spawnScript: [
      { enemyId: 'fast', statMultiplier: 2.75, spawnDelayMs: 1000 },
      { enemyId: 'ranged', statMultiplier: 2.6, spawnDelayMs: 3000 },
      { enemyId: 'aoe', statMultiplier: 2.8, spawnDelayMs: 6500 },
      { enemyId: 'support', statMultiplier: 2.8, spawnDelayMs: 10000 },
      { enemyId: 'guardian', statMultiplier: 2.7, spawnDelayMs: 13500 },
      { enemyId: 'sniper', statMultiplier: 2.85, spawnDelayMs: 17000 },
      { enemyId: 'tank', statMultiplier: 2.85, spawnDelayMs: 20500 },
    ],
  },
  {
    id: 'stage63',
    saga: 'saga3',
    displayName: 'Empire of Axies: Chapter 3, V',
    difficulty: 'Normal',
    baseXp: 104000,
    energyCost: 70,
    gemsFirstClear: 870,
    startingMoney: 6000,
    moneyAccrualPerSec: 170,
    baseHp: 950,
    restrictions: { costRange: { min: 400, max: 1600 } },
    enemyBaseHp: 35000,
    spawnScript: [
      { enemyId: 'basic', statMultiplier: 3, spawnDelayMs: 1000 },
      { enemyId: 'fast', statMultiplier: 3, spawnDelayMs: 2600 },
      { enemyId: 'swarm', statMultiplier: 3, spawnDelayMs: 5200 },
      { enemyId: 'tank', statMultiplier: 3, spawnDelayMs: 8500 },
      { enemyId: 'sniper', statMultiplier: 3, spawnDelayMs: 12000 },
      { enemyId: 'guardian', statMultiplier: 2.9, spawnDelayMs: 15500 },
      { enemyId: 'support', statMultiplier: 3, spawnDelayMs: 18500 },
      { enemyId: 'aoe', statMultiplier: 3, spawnDelayMs: 21500 },
    ],
  },
  {
    id: 'stage64',
    saga: 'saga3',
    displayName: 'Empire of Axies: Chapter 3, VI',
    difficulty: 'Hard',
    baseXp: 117000,
    energyCost: 75,
    gemsFirstClear: 950,
    startingMoney: 6000,
    moneyAccrualPerSec: 170,
    baseHp: 900,
    enemyBaseHp: 40000,
    spawnScript: [
      { enemyId: 'ranged', statMultiplier: 3, spawnDelayMs: 1000 },
      { enemyId: 'guardian', statMultiplier: 3.1, spawnDelayMs: 3500 },
      { enemyId: 'sniper', statMultiplier: 3.2, spawnDelayMs: 7000 },
      { enemyId: 'support', statMultiplier: 3.2, spawnDelayMs: 10500 },
      { enemyId: 'swarm', statMultiplier: 3.2, spawnDelayMs: 14000 },
      { enemyId: 'tank', statMultiplier: 3.2, spawnDelayMs: 17500 },
      { enemyId: 'aoe', statMultiplier: 3.2, spawnDelayMs: 21000 },
    ],
  },
  {
    id: 'stage65',
    saga: 'saga3',
    displayName: 'Empire of Axies: Chapter 3, VII',
    difficulty: 'Hard',
    baseXp: 131000,
    energyCost: 80,
    gemsFirstClear: 1040,
    startingMoney: 6000,
    moneyAccrualPerSec: 170,
    baseHp: 900,
    enemyBaseHp: 45500,
    spawnScript: [
      { enemyId: 'aoe', statMultiplier: 3.35, spawnDelayMs: 1000 },
      { enemyId: 'basic', statMultiplier: 3.35, spawnDelayMs: 2800 },
      { enemyId: 'support', statMultiplier: 3.4, spawnDelayMs: 5600 },
      { enemyId: 'sniper', statMultiplier: 3.45, spawnDelayMs: 9000 },
      { enemyId: 'guardian', statMultiplier: 3.35, spawnDelayMs: 12500 },
      { enemyId: 'tank', statMultiplier: 3.45, spawnDelayMs: 16000 },
      { enemyId: 'swarm', statMultiplier: 3.45, spawnDelayMs: 19500 },
    ],
  },
  {
    id: 'stage66',
    saga: 'saga3',
    displayName: 'Empire of Axies: Chapter 3, VIII',
    difficulty: 'Hard',
    baseXp: 147000,
    energyCost: 85,
    gemsFirstClear: 1140,
    startingMoney: 6000,
    moneyAccrualPerSec: 170,
    baseHp: 900,
    enemyBaseHp: 51500,
    spawnScript: [
      { enemyId: 'guardian', statMultiplier: 3.6, spawnDelayMs: 1000 },
      { enemyId: 'fast', statMultiplier: 3.6, spawnDelayMs: 3500 },
      { enemyId: 'sniper', statMultiplier: 3.7, spawnDelayMs: 6500 },
      { enemyId: 'support', statMultiplier: 3.7, spawnDelayMs: 10000 },
      { enemyId: 'ranged', statMultiplier: 3.5, spawnDelayMs: 13500 },
      { enemyId: 'swarm', statMultiplier: 3.7, spawnDelayMs: 17000 },
      { enemyId: 'tank', statMultiplier: 3.7, spawnDelayMs: 20500 },
      { enemyId: 'aoe', statMultiplier: 3.7, spawnDelayMs: 24000 },
    ],
  },
  {
    id: 'stage67',
    saga: 'saga3',
    displayName: 'Empire of Axies: Chapter 3, IX',
    difficulty: 'Hard',
    baseXp: 166000,
    energyCost: 89,
    gemsFirstClear: 1250,
    startingMoney: 6000,
    moneyAccrualPerSec: 170,
    baseHp: 900,
    // Restriction Stage (bible §A.6.5): full-roster gauntlet before the
    // campaign's final boss.
    restrictions: { maxDeployed: 7 },
    enemyBaseHp: 58000,
    spawnScript: [
      { enemyId: 'swarm', statMultiplier: 3.9, spawnDelayMs: 800 },
      { enemyId: 'sniper', statMultiplier: 3.95, spawnDelayMs: 2400 },
      { enemyId: 'support', statMultiplier: 3.95, spawnDelayMs: 4800 },
      { enemyId: 'tank', statMultiplier: 3.9, spawnDelayMs: 8000 },
      { enemyId: 'guardian', statMultiplier: 3.85, spawnDelayMs: 11500 },
      { enemyId: 'aoe', statMultiplier: 3.95, spawnDelayMs: 15000 },
      { enemyId: 'ranged', statMultiplier: 3.75, spawnDelayMs: 18500 },
      { enemyId: 'basic', statMultiplier: 3.95, spawnDelayMs: 22000 },
      { enemyId: 'fast', statMultiplier: 3.95, spawnDelayMs: 25500 },
    ],
  },
  {
    id: 'stage68',
    saga: 'saga3',
    displayName: 'Empire of Axies: The Ascendant',
    difficulty: 'Boss',
    baseXp: 289000,
    energyCost: 107,
    gemsFirstClear: 2130,
    startingMoney: 6000,
    moneyAccrualPerSec: 170,
    baseHp: 900,
    restrictions: { bannedUnitTypes: ['titan'] },
    allowContinue: false, // Continue (bible §A.3.9) — disabled for saga bosses, see stage10's own comment
    enemyBaseHp: 80000,
    spawnScript: [
      { enemyId: 'guardian', statMultiplier: 4.1, spawnDelayMs: 1000 },
      { enemyId: 'sniper', statMultiplier: 4.2, spawnDelayMs: 3000 },
      { enemyId: 'support', statMultiplier: 4.2, spawnDelayMs: 5500 },
      { enemyId: 'swarm', statMultiplier: 4.2, spawnDelayMs: 8000 },
      { enemyId: 'aoe', statMultiplier: 4.2, spawnDelayMs: 11000 },
      { enemyId: 'tank', statMultiplier: 4.2, spawnDelayMs: 14500 },
      { enemyId: 'ranged', statMultiplier: 4, spawnDelayMs: 18000 },
      // Base-HP%-triggered boss spawn (see stage10's own comment) — same
      // 99% trigger + isBoss shockwave, for the campaign's final boss —
      // Emperor Nyandam's strongest real-Chapter-1-boss-refight form yet.
      { enemyId: 'titan', statMultiplier: 3, baseHpPercentTrigger: 99, isBoss: true },
    ],
  },
];

// Unit cost scales per stage/chapter (bible §A.3.7) — NEVER per unit level.
// Battle Cats' own stated range is "commonly 1.0x in the earliest content,
// rising to ~1.5x-2.0x in later chapters"; mapped directly onto this game's
// 3 sagas (rather than a smooth per-stage ramp) since the bible describes it
// in exactly those chapter-bucket terms. Applied at summon time
// (GameScene.trySpawnUnit) on top of UNIT_CONFIG's own base cost — falls
// back to 1.0x for a saga-less pseudo-stage (Sparring Grounds' dojo mode).
const SAGA_COST_MULTIPLIERS = { saga1: 1.0, saga2: 1.5, saga3: 2.0 };

export function getStageCostMultiplier(stage) {
  return SAGA_COST_MULTIPLIERS[stage?.saga] ?? 1.0;
}
